<script setup lang="ts">
import StyledSelect from '../app-host/StyledSelect.vue'
import { randomUUID } from '../services/uuid'
import {computed,ref} from 'vue'
import {useQuery,useQueryClient} from '@tanstack/vue-query'
import {api,APIError,type Instance,type Task} from '../services/api'
import {useDesktop} from '../desktop/store'
import {copy,json} from '../recovery/state'
import type {ResourceRef} from '../app-host/types'

interface Snapshot {
  id:string; ownerId:string; source:ResourceRef; path:string; capturedVersion:string; created:string
  entries:number; total:number; archiveHash:string; archiveBytes:number; state:string
  consistency:{mode:string;before?:string;after?:string}; before?:{state:string;detail?:string}; after?:{state:string;detail?:string}
}
interface RestoreEntry {path:string;kind:string;size:number;hash?:string;mode:number;modified:string;targetPath:string;targetVersion:string;targetObjectId?:string}
interface RestorePlan {hash:string;archiveHash:string;archiveObjectId:string;targetRootId:string;targetObjectId?:string;total:number;created:string;entries:RestoreEntry[];request:{id:string;ownerId:string;backupId:string;target:ResourceRef;path:string;version:string}}
interface FileStat {path:string;kind:string;size:number;version:string}
interface BackupDraft {path:string;version:string;compression:'store'|'deflate';consistencyMode:'files'|'save'|'pause'|'stop'|'hooks';before:string;after:string}
interface CreateAttempt {requestId:string;path:string;version:string;state:string;taskId?:string;error?:string}
interface RestoreDraft {backupId:string;targetPath:string;targetVersion:string;planRequestId:string;restoreRequestId:string}
interface RestoreAttempt {requestId:string;state:string;taskId?:string;error?:string}
interface ScheduleSpec {id:string;ownerId:string;resource:ResourceRef;action:string;args:unknown;cron:string;timezone:string;misfire:string;overlap:string;enabled:boolean}
interface Schedule {spec:ScheduleSpec;configRevision:number;nextRun:string;pending?:string;lastSlot?:string;lastTaskId?:string;skipped:number;lastError?:string}
interface ScheduleDraft {id?:string;revision:number;action:string;cron:string;timezone:string;misfire:string;overlap:string;enabled:boolean;path:string;compression:'store'|'deflate';consistencyMode:BackupDraft['consistencyMode'];before:string;after:string;requestId:string}

const props=defineProps<{viewTabId:string;visible?:boolean}>()
const desktop=useDesktop(),recovery=desktop.recovery!,query=useQueryClient(),error=ref(''),notice=ref(''),busy=ref(false)
const view=computed(()=>recovery.state.views[props.viewTabId]!),instanceId=computed(()=>String(view.value.resourceRef?.kind==='instance'?view.value.resourceRef.id:''))
const instance=useQuery({queryKey:computed(()=>['instance',instanceId.value]),enabled:computed(()=>!!instanceId.value),queryFn:()=>api<{instance:Instance}>(`/instances/${encodeURIComponent(instanceId.value)}`).then(value=>value.instance),refetchInterval:5000})
const snapshots=useQuery({queryKey:computed(()=>['backups',instanceId.value]),enabled:computed(()=>!!instanceId.value),queryFn:()=>api<{items:Snapshot[];nextOffset:number}>(`/instances/${encodeURIComponent(instanceId.value)}/backups?offset=0&limit=100`),refetchInterval:5000})
const schedules=useQuery({queryKey:['schedules'],queryFn:()=>api<{items:Schedule[]}>('/schedules'),refetchInterval:5000})
function patch(key:string,value:unknown){if(recovery.state.views[props.viewTabId])recovery.commit([{kind:'set',path:['views',props.viewTabId,'state',key],value:json(value)}])}
function stored<T>(key:string,fallback:T):T{return (view.value.state[key] as unknown as T|undefined) ?? fallback}
const draft=computed<BackupDraft>(()=>stored('backupDraft',{path:'.',version:'',compression:'deflate',consistencyMode:'files',before:'',after:''}))
function draftField<K extends keyof BackupDraft>(key:K,value:BackupDraft[K]){patch('backupDraft',{...draft.value,[key]:value})}
const createReview=computed<CreateAttempt|undefined>({get:()=>view.value.state.backupCreate as unknown as CreateAttempt|undefined,set:value=>patch('backupCreate',value||null)})
const restoreDraft=computed<RestoreDraft>(()=>stored('backupRestoreDraft',{backupId:'',targetPath:'restored',targetVersion:'missing',planRequestId:'',restoreRequestId:''}))
function restoreField<K extends keyof RestoreDraft>(key:K,value:RestoreDraft[K]){patch('backupRestoreDraft',{...restoreDraft.value,[key]:value})}
const plan=computed<RestorePlan|undefined>(()=>view.value.state.restorePlan as unknown as RestorePlan|undefined)
const restoreAttempt=computed<RestoreAttempt|undefined>({get:()=>view.value.state.backupRestore as unknown as RestoreAttempt|undefined,set:value=>patch('backupRestore',value||null)})
const retentionKeep=computed({get:()=>Number(view.value.state.backupKeepLast??10),set:value=>patch('backupKeepLast',Math.max(1,Math.min(10000,Number(value)||1)))})
const retentionBytes=computed({get:()=>Number(view.value.state.backupMaxBytes??0),set:value=>patch('backupMaxBytes',Math.max(0,Math.min(1<<50,Number(value)||0)))})
const pruneRequestId=computed<string|undefined>({get:()=>{const value=String(view.value.state.backupPruneRequestId||'');return value||undefined},set:value=>patch('backupPruneRequestId',value||null)})
const scheduleDraft=computed<ScheduleDraft|undefined>({get:()=>view.value.state.scheduleDraft as unknown as ScheduleDraft|undefined,set:value=>patch('scheduleDraft',value||null)})
const scheduleDeleteRequests=computed<Record<string,string>>({get:()=>stored('scheduleDeleteRequests',{} as Record<string,string>),set:value=>patch('scheduleDeleteRequests',value)})
const localSchedules=computed(()=>schedules.data.value?.items.filter(item=>item.spec.resource.kind==='instance'&&item.spec.resource.id===instanceId.value&&(!item.spec.resource.nodeId||item.spec.resource.nodeId===instance.data.value?.nodeId))||[])
const selectedSnapshot=computed(()=>snapshots.data.value?.items.find(item=>item.id===restoreDraft.value.backupId))
const busyTask=computed(()=>createReview.value?.taskId||restoreAttempt.value?.taskId)
function stat(path:string){return api<FileStat>(`/instances/${encodeURIComponent(instanceId.value)}/files/stat?path=${encodeURIComponent(path)}`)}
async function prepareCreate(){
  error.value='';notice.value='';if(!draft.value.path.trim())return void(error.value='备份路径不能为空');busy.value=true
  try{const entry=await stat(draft.value.path.trim());if(!entry.version)throw new Error('节点没有返回可核对的源版本');draftField('path',entry.path||draft.value.path.trim());draftField('version',entry.version);createReview.value={requestId:randomUUID(),path:entry.path||draft.value.path.trim(),version:entry.version,state:'PREPARED'}}catch(e){error.value=String(e)}finally{busy.value=false}
}
async function createBackup(){const fixed=createReview.value;if(!fixed||busy.value)return;busy.value=true;error.value='';createReview.value={...fixed,state:'SUBMITTING'}
  try{const {task}=await api<{task:Task}>(`/instances/${encodeURIComponent(instanceId.value)}/backups`,{method:'POST',headers:{'Idempotency-Key':fixed.requestId},body:JSON.stringify({path:fixed.path,version:fixed.version,compression:draft.value.compression,consistency:{mode:draft.value.consistencyMode,before:draft.value.before||undefined,after:draft.value.after||undefined}})});createReview.value={...fixed,state:task.state,taskId:task.taskId};notice.value='备份任务已接受；完成前不会把快照显示为成功';await query.invalidateQueries({queryKey:['tasks']})}catch(e){createReview.value={...fixed,state:e instanceof APIError&&e.status<500?'REJECTED':'UNKNOWN',error:String(e)}}finally{busy.value=false}
}
async function prune(){if(busy.value||!instanceId.value)return;busy.value=true;error.value='';const requestId=pruneRequestId.value||randomUUID();if(!pruneRequestId.value)pruneRequestId.value=requestId;try{const {task}=await api<{task:Task}>(`/instances/${encodeURIComponent(instanceId.value)}/backups/prune`,{method:'POST',headers:{'Idempotency-Key':requestId},body:JSON.stringify({keepLast:retentionKeep.value,maxAge:0,maxBytes:retentionBytes.value})});pruneRequestId.value=undefined;notice.value=`保留策略任务已接受：${task.taskId}`;await query.invalidateQueries({queryKey:['tasks']})}catch(e){error.value=String(e)}finally{busy.value=false}}
async function prepareRestore(snapshot:Snapshot){const target=restoreDraft.value.targetPath||'restored';const planRequestId=restoreDraft.value.backupId===snapshot.id&&restoreDraft.value.targetPath===target&&restoreDraft.value.planRequestId?restoreDraft.value.planRequestId:randomUUID();restoreField('backupId',snapshot.id);restoreField('targetPath',target);restoreField('planRequestId',planRequestId);if(!restoreDraft.value.restoreRequestId)restoreField('restoreRequestId',randomUUID());patch('restorePlan',null);restoreAttempt.value=undefined;error.value='';notice.value='';busy.value=true
  try{let version='missing';try{version=(await stat(restoreDraft.value.targetPath||'restored')).version}catch(e){if(!(e instanceof APIError&&e.status===404))throw e}restoreField('targetVersion',version);const fixed={...restoreDraft.value,backupId:snapshot.id,targetVersion:version};const response=await api<{plan:RestorePlan;entryCount:number;nextOffset:number}>(`/instances/${encodeURIComponent(instanceId.value)}/restore-plans`,{method:'POST',headers:{'Idempotency-Key':fixed.planRequestId},body:JSON.stringify({backupId:snapshot.id,path:fixed.targetPath||'restored',version})});patch('restorePlan',response.plan);patch('restoreEntryCount',response.entryCount);notice.value=`恢复计划已生成，共 ${response.entryCount} 项；覆盖动作仍需单独确认`}catch(e){error.value=String(e)}finally{busy.value=false}}
async function loadPlan(){const id=restoreDraft.value.backupId;if(!id)return;const snapshot=snapshots.data.value?.items.find(item=>item.id===id);if(snapshot)await prepareRestore(snapshot)}
async function executeRestore(){const current=plan.value;if(!current||busy.value)return;busy.value=true;error.value='';const fixed=restoreAttempt.value||{requestId:restoreDraft.value.restoreRequestId||randomUUID(),state:'PREPARED'};restoreField('restoreRequestId',fixed.requestId);restoreAttempt.value={...fixed,state:'SUBMITTING'}
  try{const {task}=await api<{task:Task}>(`/instances/${encodeURIComponent(instanceId.value)}/restores`,{method:'POST',headers:{'Idempotency-Key':fixed.requestId},body:JSON.stringify({planId:current.request.id,planHash:current.hash,overwritePlanHash:current.hash})});restoreAttempt.value={...fixed,state:task.state,taskId:task.taskId};notice.value='恢复任务已接受；请在任务中心核对真实结果';await query.invalidateQueries({queryKey:['tasks']})}catch(e){restoreAttempt.value={...fixed,state:e instanceof APIError&&e.status<500?'REJECTED':'UNKNOWN',error:String(e)}}finally{busy.value=false}}
function newSchedule(){scheduleDraft.value={revision:0,action:'backup.create',cron:'0 3 * * *',timezone:'Asia/Shanghai',misfire:'skip',overlap:'skip',enabled:true,path:draft.value.path||'.',compression:draft.value.compression,consistencyMode:draft.value.consistencyMode,before:draft.value.before,after:draft.value.after,requestId:randomUUID()}}
function editSchedule(item:Schedule){const args=item.spec.args as {path?:string;compression?:'store'|'deflate';consistency?:{mode?:BackupDraft['consistencyMode'];before?:string;after?:string}}|undefined;const consistency=args?.consistency; scheduleDraft.value={id:item.spec.id,revision:item.configRevision,action:item.spec.action,cron:item.spec.cron,timezone:item.spec.timezone,misfire:item.spec.misfire,overlap:item.spec.overlap,enabled:item.spec.enabled,path:args?.path||draft.value.path||'.',compression:args?.compression||'deflate',consistencyMode:consistency?.mode||'files',before:consistency?.before||'',after:consistency?.after||'',requestId:randomUUID()}}
function scheduleField<K extends keyof ScheduleDraft>(key:K,value:ScheduleDraft[K]){if(scheduleDraft.value)scheduleDraft.value={...scheduleDraft.value,[key]:value}}
function scheduleArgs(d:ScheduleDraft){return d.action==='backup.create'?{path:d.path,compression:d.compression,consistency:{mode:d.consistencyMode,before:d.before||undefined,after:d.after||undefined}}:{}}
async function saveSchedule(){const d=scheduleDraft.value;if(!d||busy.value||!instance.data.value)return;busy.value=true;error.value='';const fixed=copy(d);try{const body={revision:fixed.revision,resource:{kind:'instance',id:instanceId.value,nodeId:instance.data.value.nodeId},action:fixed.action,args:scheduleArgs(fixed),cron:fixed.cron,timezone:fixed.timezone,misfire:fixed.misfire,overlap:fixed.overlap,enabled:fixed.enabled};const path=fixed.id?`/schedules/${encodeURIComponent(fixed.id)}`:'/schedules';const {schedule}=await api<{schedule:Schedule}>(path,{method:fixed.id?'PUT':'POST',headers:{'Idempotency-Key':fixed.requestId},body:JSON.stringify(body)});scheduleDraft.value=undefined;notice.value=`定时任务已保存，下次执行 ${new Date(schedule.nextRun).toLocaleString()}`;await schedules.refetch()}catch(e){error.value=String(e)}finally{busy.value=false}}
async function deleteSchedule(item:Schedule){if(!confirm('删除此定时任务？已接受的任务不会被取消。'))return;busy.value=true;error.value='';const requestId=scheduleDeleteRequests.value[item.spec.id]||randomUUID();if(!scheduleDeleteRequests.value[item.spec.id])scheduleDeleteRequests.value={...scheduleDeleteRequests.value,[item.spec.id]:requestId};try{await api(`/schedules/${encodeURIComponent(item.spec.id)}`,{method:'DELETE',headers:{'Idempotency-Key':requestId},body:JSON.stringify({revision:item.configRevision})});const next={...scheduleDeleteRequests.value};delete next[item.spec.id];scheduleDeleteRequests.value=next;notice.value='定时任务已删除';await schedules.refetch()}catch(e){error.value=String(e)}finally{busy.value=false}}
function openTask(id?:string){if(id)desktop.open({appId:'blora.tasks',resourceRef:{kind:'task',id},disposition:'dedicated',title:'备份任务'})}
</script>

<template>
  <div class="application backup-app">
    <template v-if="instanceId">
      <header class="app-heading"><div><span class="eyebrow">BACKUP & SCHEDULES</span><h2>{{instance.data.value?.name||'实例'}} · 备份</h2><p>备份先核对来源版本；恢复先生成不可变计划，覆盖必须再次确认。</p></div><button @click="snapshots.refetch();schedules.refetch()">↻ 刷新</button></header>
      <p v-if="error||instance.error.value||snapshots.error.value||schedules.error.value" class="error notice" role="alert">{{error||instance.error.value?.message||snapshots.error.value?.message||schedules.error.value?.message}}</p><p v-if="notice" class="notice" role="status">{{notice}}</p>
      <section><h3>创建备份</h3><div class="filterbar"><label>来源路径 <input :value="draft.path" aria-label="备份来源路径" placeholder=". 或 data" @input="draftField('path',($event.target as HTMLInputElement).value)"></label><label>压缩 <StyledSelect :value="draft.compression" aria-label="备份压缩方式" @change="draftField('compression',($event.target as HTMLSelectElement).value as 'store'|'deflate')"><option value="deflate">Deflate</option><option value="store">Store</option></StyledSelect></label><label>一致性 <StyledSelect :value="draft.consistencyMode" aria-label="备份一致性策略" @change="draftField('consistencyMode',($event.target as HTMLSelectElement).value as BackupDraft['consistencyMode'])"><option value="files">文件版本核对</option><option value="save">应用保存（需节点适配）</option><option value="pause">暂停应用（需节点适配）</option><option value="stop">停止应用（需节点适配）</option><option value="hooks">配置钩子（需节点适配）</option></StyledSelect></label><button class="primary" :disabled="busy" @click="prepareCreate">读取版本并预览</button></div><p class="muted">当前版本：{{draft.version||'尚未读取'}}。save/pause/stop/hooks 只有在 Daemon 配置了真实 HookRunner 时才会接受，不能用文件打包冒充一致性。</p><div v-if="createReview" class="in-window-dialog" role="dialog" aria-label="确认创建备份"><h3>确认创建备份</h3><p>{{createReview.path}} · {{createReview.version}}</p><p>策略：{{draft.consistencyMode}} · {{draft.compression}}</p><p v-if="createReview.error" class="error">{{createReview.error}}</p><p v-if="createReview.taskId">任务 {{createReview.taskId}} · {{createReview.state}}</p><div class="action-row"><button type="button" :disabled="busy||createReview.state==='SUBMITTING'" @click="createReview=undefined">返回修改</button><button v-if="createReview.taskId" type="button" @click="openTask(createReview.taskId)">查看任务</button><button v-else class="primary" :disabled="busy" @click="createBackup">确认创建备份</button></div></div></section>
      <section><div class="action-row"><h3>可恢复快照</h3><button :disabled="busy" @click="prune">按保留策略清理</button></div><div class="filterbar"><label>保留最近 <input v-model.number="retentionKeep" aria-label="保留快照数量" type="number" min="1" max="10000"></label><label>最大仓库字节 <input v-model.number="retentionBytes" aria-label="备份仓库最大字节" type="number" min="0"></label></div><article v-for="item in snapshots.data.value?.items" :key="item.id" class="task-row"><span><strong>{{item.path}}</strong> · {{item.state}} · {{new Date(item.created).toLocaleString()}}<small>{{item.entries}} 项 / {{item.total}} 字节 · {{item.consistency.mode}} · {{item.id}}</small></span><span class="action-row"><button :disabled="busy||item.state!=='ready'" @click="prepareRestore(item)">生成恢复计划</button></span></article><p v-if="!snapshots.isPending.value&&!snapshots.data.value?.items.length" class="empty-state">尚无已完成快照。正在执行的任务不会提前显示为成功。</p></section>
      <section><h3>恢复计划</h3><div class="filterbar"><label>快照 ID <input :value="restoreDraft.backupId" aria-label="恢复快照 ID" placeholder="从上方选择或粘贴" @input="restoreField('backupId',($event.target as HTMLInputElement).value)"></label><label>目标路径 <input :value="restoreDraft.targetPath" aria-label="恢复目标路径" @input="restoreField('targetPath',($event.target as HTMLInputElement).value)"></label><button :disabled="busy||!selectedSnapshot" @click="loadPlan">重新生成计划</button></div><div v-if="plan" class="restore-plan"><p>计划 {{plan.request.id}} · {{plan.entries.length}}/{{Number(view.state.restoreEntryCount||plan.entries.length)}} 项 · hash {{plan.hash}}</p><p class="muted">目标版本 {{plan.request.version}}。计划中的现有文件会在服务端再次按原 hash 核对。</p><article v-for="entry in plan.entries.slice(0,100)" :key="entry.targetPath" class="task-row"><span>{{entry.targetPath}} · {{entry.kind}} · {{entry.size}} 字节</span><span>{{entry.targetVersion==='missing'?'新建':'将覆盖'}}</span></article><p v-if="plan.entries.length<Number(view.state.restoreEntryCount||plan.entries.length)" class="warning">计划清单已分页显示；服务端仍以完整不可变计划执行。</p><div v-if="restoreAttempt" class="notice"><span>恢复任务：{{restoreAttempt.taskId||'回执待核对'}} · {{restoreAttempt.state}}</span><p v-if="restoreAttempt.error" class="error">{{restoreAttempt.error}}</p><button v-if="restoreAttempt.taskId" @click="openTask(restoreAttempt.taskId)">查看任务</button></div><div class="action-row"><button class="primary" :disabled="busy||!!restoreAttempt?.taskId" @click="executeRestore">确认覆盖此恢复计划</button><button v-if="restoreAttempt?.state==='UNKNOWN'" :disabled="busy" @click="executeRestore">用原请求核对恢复</button></div></div><p v-else class="muted">先选择一个已完成快照并生成计划。目标路径默认恢复到 {{restoreDraft.targetPath}}。</p></section>
      <section><div class="action-row"><h3>定时任务</h3><button @click="newSchedule">＋ 新建计划</button></div><article v-for="item in localSchedules" :key="item.spec.id" class="task-row"><span><strong>{{item.spec.action}}</strong> · {{item.spec.cron}} · {{item.spec.timezone}} · {{item.spec.enabled?'启用':'停用'}}<small>下次 {{new Date(item.nextRun).toLocaleString()}} · v{{item.configRevision}}{{item.lastError?' · '+item.lastError:''}}</small></span><span class="action-row"><button @click="editSchedule(item)">编辑</button><button @click="deleteSchedule(item)">删除</button></span></article><p v-if="!localSchedules.length" class="muted">此实例尚无定时任务；计划创建者失去权限后触发会被服务端拒绝。</p><form v-if="scheduleDraft" class="in-window-dialog" role="dialog" aria-label="编辑定时任务" @submit.prevent="saveSchedule"><h3>{{scheduleDraft.id?'编辑':'新建'}}定时任务</h3><label>动作 <StyledSelect :value="scheduleDraft.action" aria-label="定时任务动作" @change="scheduleField('action',($event.target as HTMLSelectElement).value)"><option value="backup.create">创建备份</option><option value="instance.start">启动实例</option><option value="instance.stop">停止实例</option><option value="instance.restart">重启实例</option></StyledSelect></label><label>Cron（五段）<input :value="scheduleDraft.cron" aria-label="定时任务 Cron" required @input="scheduleField('cron',($event.target as HTMLInputElement).value)"></label><label>时区<input :value="scheduleDraft.timezone" aria-label="定时任务时区" required @input="scheduleField('timezone',($event.target as HTMLInputElement).value)"></label><template v-if="scheduleDraft.action==='backup.create'"><label>备份路径<input :value="scheduleDraft.path" aria-label="计划备份路径" required @input="scheduleField('path',($event.target as HTMLInputElement).value)"></label><label>压缩 <StyledSelect :value="scheduleDraft.compression" aria-label="计划备份压缩" @change="scheduleField('compression',($event.target as HTMLSelectElement).value as 'store'|'deflate')"><option value="deflate">Deflate</option><option value="store">Store</option></StyledSelect></label></template><label>错过执行 <StyledSelect :value="scheduleDraft.misfire" aria-label="错过执行策略" @change="scheduleField('misfire',($event.target as HTMLSelectElement).value)"><option value="skip">跳过</option><option value="run_once">恢复后运行一次</option></StyledSelect></label><label>重叠 <StyledSelect :value="scheduleDraft.overlap" aria-label="重叠策略" @change="scheduleField('overlap',($event.target as HTMLSelectElement).value)"><option value="skip">跳过</option><option value="wait_one">等待一次</option></StyledSelect></label><label class="check-row"><input :checked="scheduleDraft.enabled" type="checkbox" @change="scheduleField('enabled',($event.target as HTMLInputElement).checked)">启用（保存时重新校验权限）</label><p class="muted">调度只在 Master 在线且节点在线、权限仍有效时接受任务；节点离线不会由 Daemon 私自补跑。</p><div class="action-row"><button type="button" :disabled="busy" @click="scheduleDraft=undefined">返回</button><button class="primary" :disabled="busy">保存定时任务</button></div></form></section>
      <section v-if="scheduleDraft?.action==='backup.create'" class="in-window-dialog" aria-label="定时备份一致性"><h3>定时备份一致性</h3><label>一致性 <StyledSelect :value="scheduleDraft.consistencyMode" aria-label="计划备份一致性策略" @change="scheduleField('consistencyMode',($event.target as HTMLSelectElement).value as BackupDraft['consistencyMode'])"><option value="files">文件版本核对</option><option value="save">应用保存（需节点适配）</option><option value="pause">暂停应用（需节点适配）</option><option value="stop">停止应用（需节点适配）</option><option value="hooks">配置钩子（需节点适配）</option></StyledSelect></label><label v-if="scheduleDraft.consistencyMode!=='files'">保存前钩子引用<input :value="scheduleDraft.before" aria-label="计划保存前钩子引用" maxlength="128" @input="scheduleField('before',($event.target as HTMLInputElement).value)"></label><label v-if="scheduleDraft.consistencyMode!=='files'">保存后钩子引用<input :value="scheduleDraft.after" aria-label="计划保存后钩子引用" maxlength="128" @input="scheduleField('after',($event.target as HTMLInputElement).value)"></label><p class="muted">保存/暂停/停止/钩子策略要求节点配置对应的 HookRunner。</p></section>
    </template>
    <div v-else class="empty-state"><h3>备份应用需要实例资源</h3><p>请从实例中心打开具体实例的备份窗口。</p></div>
  </div>
</template>
