<script setup lang="ts">
import { randomUUID } from '../services/uuid'
import {computed,ref,onMounted,onBeforeUnmount,watch} from 'vue'
import {useQuery} from '@tanstack/vue-query'
import {useDesktop} from '../desktop/store'
import {api,type Node,type Task} from '../services/api'
import {dockerQuery,dockerPath,type DockerSnapshot,type DockerOperation,type DockerObject} from '../services/containers'
import {copy,json} from '../recovery/state'
import ComposeEditor from './ComposeEditor.vue'
import DockerLogs from './DockerLogs.vue'
interface Pending {nodeId:string;requestId:string;operation:DockerOperation;taskId?:string;state?:string;phase?:string;error?:string}
const props=defineProps<{viewTabId:string;visible:boolean}>(),desktop=useDesktop(),recovery=desktop.recovery!,original=recovery.state.views[props.viewTabId]!,view=computed(()=>recovery.state.views[props.viewTabId]||original),error=ref(''),busy=ref(false),snapshot=ref<DockerSnapshot>(),detail=ref<DockerSnapshot>()
function patch(key:string,value:unknown){if(recovery.state.views[props.viewTabId])recovery.commit([{kind:'set',path:['views',props.viewTabId,'state',key],value:json(value)}])}
const nodeId=computed({get:()=>String(view.value.state.nodeId||view.value.resourceRef?.nodeId||''),set:v=>{patch('nodeId',v);snapshot.value=undefined;detail.value=undefined;patch('project',null);patch('logs',null)}}),kind=computed({get:()=>String(view.value.state.kind||'containers'),set:v=>{patch('kind',v);patch('project',null);patch('logs',null);detail.value=undefined}}),pending=computed(()=>view.value.state.pending as unknown as Pending|undefined),dialog=computed(()=>view.value.state.dialog as unknown as Pending|undefined),project=computed(()=>view.value.state.project as {id:string;revision:number}|undefined),logs=computed(()=>view.value.state.logs as {id:string}|undefined)
const nodes=useQuery({queryKey:['managed-nodes'],queryFn:()=>api<{items:Node[]}>('/nodes/managed')})
const name=computed({get:()=>String(view.value.state.newName||''),set:v=>patch('newName',v)}),image=computed({get:()=>String(view.value.state.newImage||''),set:v=>patch('newImage',v)}),config=computed({get:()=>String(view.value.state.newConfig||'{"Cmd":["sleep","3600"]}'),set:v=>patch('newConfig',v)})
let timer:ReturnType<typeof setTimeout>|undefined,disposed=false,loadGeneration=0
async function load(){if(!nodeId.value)return;const generation=++loadGeneration;error.value='';try{const result=await dockerQuery(nodeId.value,{kind:kind.value,limit:100});if(!disposed&&generation===loadGeneration)snapshot.value=result}catch(e){if(generation===loadGeneration){snapshot.value=undefined;error.value=String(e)}}}
watch([nodeId,kind],()=>void load());watch(()=>nodes.data.value,items=>{if(!nodeId.value&&items?.items.length)nodeId.value=items.items[0]!.nodeId},{immediate:true})
function ask(operation:DockerOperation){if(!nodeId.value)return;patch('dialog',{nodeId:nodeId.value,requestId:randomUUID(),operation:copy(operation)})}
watch(project,(value,old)=>{if(value?.id!==old?.id)patch('composeDraftId',null)},{flush:'sync'})
async function create(){try{if(kind.value==='projects'){if(!/^[a-zA-Z0-9][a-zA-Z0-9_.-]{0,63}$/.test(name.value))throw new Error('项目标识需要 1～64 个字母、数字、点、下划线或横线');patch('project',{id:name.value,revision:0});return}if(kind.value==='containers'){const parsed=JSON.parse(config.value);if(!parsed||Array.isArray(parsed)||typeof parsed!=='object')throw new Error('容器配置需要 JSON 对象');ask({action:'container.create',name:name.value,config:{...parsed,Image:image.value}})}else if(kind.value==='images')ask({action:'image.pull',image:image.value});else ask({action:kind.value==='volumes'?'volume.create':'network.create',name:name.value})}catch(e){error.value=String(e)}}
async function submit(fixed:Pending){if(busy.value)return;busy.value=true;patch('pending',{...fixed,state:'SUBMITTING'});patch('dialog',null);error.value='';try{const {task}=await api<{task:Task}>(`${dockerPath(fixed.nodeId)}/actions`,{method:'POST',headers:{'Idempotency-Key':fixed.requestId},body:JSON.stringify(fixed.operation)});patch('pending',{...fixed,taskId:task.taskId,state:task.state,phase:task.phase});await reconcile()}catch(e){error.value=String(e);patch('pending',{...fixed,state:'UNCONFIRMED',error:String(e)})}finally{busy.value=false}}
async function reconcile(){if(timer)clearTimeout(timer);const fixed=pending.value;if(!fixed||disposed)return;try{const task=fixed.taskId?(await api<{task:Task}>(`/tasks/${encodeURIComponent(fixed.taskId)}`)).task:(await api<{items:Task[]}>('/tasks')).items.find(t=>t.requestId===fixed.requestId);if(!task)return;if(disposed)return;patch('pending',{...fixed,taskId:task.taskId,state:task.state,phase:task.phase,error:task.error});if(!['SUCCEEDED','FAILED','CANCELLED','INTERRUPTED'].includes(task.state))timer=setTimeout(()=>void reconcile(),1500);else await load()}catch(e){error.value=String(e)}}
async function inspect(item:DockerObject){try{detail.value=await dockerQuery(nodeId.value,{kind:item.target.kind,target:item.target,details:true})}catch(e){error.value=String(e)}}
function terminal(item:DockerObject){desktop.open({appId:'blora.terminal',resourceRef:{kind:'node',id:nodeId.value,nodeId:nodeId.value},title:item.name+' · 容器终端',disposition:'new-window',state:{containerId:item.target.id||'',containerTarget:json(item.target)}})}
onMounted(()=>{void load();if(pending.value)void reconcile()});onBeforeUnmount(()=>{disposed=true;if(timer)clearTimeout(timer)})
</script>
<template><div class="application docker-app"><header class="app-heading"><div><span class="eyebrow">DOCKER & COMPOSE</span><h2>容器中心</h2><p>按节点管理真实容器、镜像与项目。</p></div><button @click="load">刷新资源</button></header><div class="filterbar"><label>管理节点<select v-model="nodeId" aria-label="Docker 管理节点"><option value="">选择获准节点</option><option v-for="node in nodes.data.value?.items" :key="node.nodeId" :value="node.nodeId">{{node.name}} · {{node.state}}</option></select></label><select v-model="kind" aria-label="Docker 资源类别"><option value="containers">容器</option><option value="images">镜像</option><option value="volumes">数据卷</option><option value="networks">网络</option><option value="projects">Compose 项目</option><option value="capabilities">节点能力</option></select></div><p v-if="error||nodes.error.value" class="error" role="alert">{{error||nodes.error.value?.message}}</p><p v-if="!nodes.isPending.value&&!nodes.data.value?.items.length" class="empty-state">没有获准的主机管理节点。</p>
<section v-if="pending" class="notice" role="status"><strong>{{pending.operation.action}} · {{pending.state}} · {{pending.phase}}</strong><p>{{pending.nodeId}} · {{pending.taskId||'回执待核对'}}</p><p v-if="pending.error" class="error">{{pending.error}}</p><button @click="reconcile">核对结果</button><button v-if="!pending.taskId" :disabled="busy" @click="submit(copy(pending))">重试原请求</button><button v-if="pending.taskId" @click="desktop.open({appId:'blora.tasks',resourceRef:{kind:'task',id:pending.taskId},disposition:'new-window'})">查看任务</button></section>
<template v-if="nodeId"><template v-if="project"><button @click="patch('project',null);load()">返回项目列表</button><ComposeEditor :key="nodeId+':'+project.id" :view-tab-id="viewTabId" :node-id="nodeId" :project-id="project.id" :revision="project.revision"/></template><template v-else-if="logs"><button @click="patch('logs',null)">返回容器列表</button><DockerLogs :key="nodeId+':'+logs.id" :node-id="nodeId" :container-id="logs.id"/></template><template v-else>
<form v-if="kind!=='capabilities'" class="docker-create" @submit.prevent="create"><label v-if="kind!=='images'">{{kind==='projects'?'项目标识':'名称'}}<input v-model="name" aria-label="Docker 新资源名称" required></label><label v-if="kind==='containers'||kind==='images'">镜像引用<input v-model="image" aria-label="Docker 镜像引用" required placeholder="仓库/镜像:版本"></label><label v-if="kind==='containers'">Docker 创建配置 JSON<textarea v-model="config" aria-label="Docker 创建配置" rows="3"></textarea></label><button :disabled="busy">{{kind==='projects'?'新建配置草稿':kind==='images'?'拉取镜像…':'创建…'}}</button></form>
<p v-if="snapshot" class="muted">观察时间 {{new Date(snapshot.observedAt).toLocaleString()}}<span v-if="snapshot.truncated"> · 当前结果已截断，请缩小查询范围</span></p><pre v-if="snapshot?.capabilities" class="selectable">{{JSON.stringify(snapshot.capabilities,null,2)}}</pre>
<article v-for="item in snapshot?.items" :key="item.target.id||item.target.name" class="docker-object" :data-docker-id="item.target.id||item.target.name"><strong>{{item.name}}</strong><p>{{item.state}} {{item.health}} · {{item.image}}</p><small class="selectable">{{item.target.id||item.target.name}} · {{item.target.createdAt}}</small><div class="action-row"><button @click="inspect(item)">详情</button><template v-if="kind==='containers'"><button v-for="action in ['start','stop','restart']" :key="action" @click="ask({action:'container.'+action,target:item.target,stopSeconds:30})">{{({start:'启动',stop:'停止',restart:'重启'} as Record<string,string>)[action]}}…</button><button @click="patch('logs',{id:item.target.id})">日志</button><button @click="terminal(item)">终端</button></template><button @click="ask({action:item.target.kind+'.delete',target:item.target})">删除…</button></div></article>
<article v-for="item in snapshot?.projects" :key="item.id" class="docker-object" :data-project-id="item.id"><strong>{{item.id}}</strong><p>保存版本 {{item.revision}} · 已应用版本 {{item.appliedRevision}} · {{item.deleted?'已删除部署':'项目记录'}}</p><div class="action-row"><button @click="patch('composeDraftId',null);patch('project',{id:item.id,revision:item.revision})">编辑配置</button><button @click="ask({action:'compose.apply',projectId:item.id,revision:item.revision,pullPolicy:'missing',healthSeconds:60})">应用此版本…</button><button @click="ask({action:'compose.delete',projectId:item.id,revision:item.revision})">删除部署…</button></div></article><pre v-if="detail" class="docker-detail selectable">{{JSON.stringify(detail,null,2)}}</pre></template></template>
<form v-if="dialog" class="in-window-dialog" role="dialog" aria-label="确认 Docker 操作" @submit.prevent="submit(copy(dialog))"><h3>确认 {{dialog.operation.action}}</h3><p>节点 {{dialog.nodeId}}</p><pre class="selectable">{{JSON.stringify(dialog.operation,null,2)}}</pre><p v-if="dialog.operation.action.endsWith('.delete')">此请求仅删除列出的对象。删除容器或项目部署保留数据卷；删除数据卷需在数据卷列表单独确认。</p><p>提交后由节点执行，结果在任务中心记录；关闭窗口不取消任务。</p><div class="action-row"><button type="button" @click="patch('dialog',null)">返回</button><button class="primary" :disabled="busy">确认执行</button></div></form></div></template>
<style scoped>.docker-create{display:flex;flex-wrap:wrap;gap:10px;padding:12px;background:var(--surface-low)}.docker-create label{display:flex;flex-direction:column;gap:5px}.docker-create textarea{min-width:300px;font-family:monospace}.docker-object{padding:14px;border-bottom:1px solid var(--line)}.docker-object small{overflow-wrap:anywhere}.docker-detail{white-space:pre-wrap;max-height:360px;overflow:auto}.docker-app{display:flex;flex-direction:column}.docker-app pre{white-space:pre-wrap;overflow-wrap:anywhere}</style>
