<script setup lang="ts">
import {computed,onMounted,ref} from 'vue'
import {useQueryClient} from '@tanstack/vue-query'
import {api,APIError,type Instance} from '../services/api'
import {useDesktop} from '../desktop/store'
import {copy,json} from '../recovery/state'
import InstanceConfigFields from './InstanceConfigFields.vue'
interface SettingsDraft {revision:number;name:string;group:string;tags:string;includeConfig:boolean;config:Record<string,unknown>;advanced:boolean;raw:string}
interface Submission {requestId:string;instanceId:string;nodeId:string;body:Record<string,unknown>;state:string;error?:string}
const props=defineProps<{viewTabId:string;instance:Instance}>(),desktop=useDesktop(),recovery=desktop.recovery!,query=useQueryClient(),busy=ref(false),error=ref(''),notice=ref('')
const view=computed(()=>recovery.state.views[props.viewTabId]!)
function patch(key:string,value:unknown){if(recovery.state.views[props.viewTabId])recovery.commit([{kind:'set',path:['views',props.viewTabId,'state',key],value:json(value)}])}
function initial(instance:Instance):SettingsDraft{return{revision:instance.configRevision??instance.revision,name:instance.name,group:instance.group||'',tags:(instance.tags||[]).join(', '),includeConfig:false,config:copy(instance.config),advanced:false,raw:JSON.stringify(instance.config,null,2)}}
const draft=computed(()=>view.value.state.settingsDraft as unknown as SettingsDraft||initial(props.instance)),submission=computed<Submission|undefined>({get:()=>view.value.state.settingsSubmission as unknown as Submission|undefined,set:value=>patch('settingsSubmission',value||null)})
function field(key:string,value:unknown){patch('settingsDraft',{...draft.value,[key]:value})}
function config(value:Record<string,unknown>){patch('settingsDraft',{...draft.value,config:value,raw:JSON.stringify(value,null,2)})}
function review(){error.value='';try{const config=draft.value.advanced?JSON.parse(draft.value.raw):draft.value.config;if(!config||typeof config!=='object'||Array.isArray(config))throw new Error('运行配置必须是 JSON 对象');submission.value={instanceId:props.instance.instanceId,nodeId:props.instance.nodeId,requestId:crypto.randomUUID(),state:'PREPARED',body:{revision:draft.value.revision,name:draft.value.name,group:draft.value.group,tags:draft.value.tags.split(',').map(value=>value.trim()).filter(Boolean),...draft.value.includeConfig?{config}:{}}}}catch(e){error.value=String(e)}}
async function submit(){if(!submission.value||busy.value)return;const fixed=copy(submission.value);busy.value=true;submission.value={...fixed,state:'SUBMITTING'};try{const {instance}=await api<{instance:Instance}>(`/instances/${encodeURIComponent(fixed.instanceId)}`,{method:'PATCH',headers:{'Idempotency-Key':fixed.requestId},body:JSON.stringify(fixed.body)});patch('settingsDraft',initial(instance));submission.value=undefined;notice.value='配置已保存，没有启动或重启实例';await query.invalidateQueries({queryKey:['instances']})}catch(e){submission.value={...fixed,state:e instanceof APIError&&e.status<500?'REJECTED':'UNKNOWN',error:String(e)}}finally{busy.value=false}}
async function reread(){if(submission.value)return;try{const {instance}=await api<{instance:Instance}>(`/instances/${encodeURIComponent(props.instance.instanceId)}`);patch('settingsServer',initial(instance))}catch(e){error.value=String(e)}}
const server=computed(()=>view.value.state.settingsServer as unknown as SettingsDraft|undefined)
onMounted(()=>{if(!view.value.state.settingsDraft)patch('settingsDraft',initial(props.instance))})
</script>
<template>
  <form class="instance-settings" @submit.prevent="review"><p v-if="notice" role="status">{{notice}}</p><p v-if="error" class="error">{{error}}</p><p v-if="draft.revision!==(instance.configRevision??instance.revision)" class="warning">服务器配置版本已变化，草稿仍基于 {{draft.revision}}；提交时将核对版本，不会自动覆盖。</p><fieldset :disabled="!!submission"><legend>配置版本 {{draft.revision}}</legend><label>实例名称<input :value="draft.name" required maxlength="120" @input="field('name',($event.target as HTMLInputElement).value)"></label><label>分组<input :value="draft.group" @input="field('group',($event.target as HTMLInputElement).value)"></label><label>标签（逗号分隔）<input :value="draft.tags" @input="field('tags',($event.target as HTMLInputElement).value)"></label><label class="check-row"><input type="checkbox" :checked="draft.includeConfig" @change="field('includeConfig',($event.target as HTMLInputElement).checked)">同时修改运行配置</label><template v-if="draft.includeConfig"><label class="check-row"><input type="checkbox" :checked="draft.advanced" @change="field('advanced',($event.target as HTMLInputElement).checked)">高级 JSON 编辑</label><textarea v-if="draft.advanced" class="config-raw" :value="draft.raw" aria-label="高级运行配置JSON" rows="18" @input="field('raw',($event.target as HTMLTextAreaElement).value)"></textarea><InstanceConfigFields v-else :config="draft.config" @change="config" /></template><p class="muted">名称、分组和标签可在运行中修改。启动命令等变更需要实例已停止且无待执行任务；停止策略和自动启动可在运行中保存。运行配置仍由服务端校验权限。</p><div class="action-row"><button class="primary">核对配置变更</button><button type="button" @click="reread">读取服务器配置作比较</button></div></fieldset>
    <section v-if="server" class="config-comparison"><h4>服务器配置版本 {{server.revision}}</h4><pre>{{JSON.stringify(server,null,2)}}</pre><button type="button" :disabled="!!submission" @click="patch('settingsDraft',server);patch('settingsServer',null)">用服务器配置替换此表单草稿</button></section>
    <div v-if="submission" class="in-window-dialog" role="dialog" aria-label="确认实例配置"><h3>确认保存实例配置</h3><p>{{submission.nodeId}} / {{submission.instanceId}}</p><p>原配置版本：{{submission.body.revision}}</p><pre>{{JSON.stringify(submission.body,null,2)}}</pre><p>本次仅保存配置。{{submission.state==='UNKNOWN'?'保存回执不明；再次确认用原请求身份核对。':''}}刷新不会提交。</p><p v-if="submission.error" class="error">{{submission.error}}</p><div class="action-row"><button type="button" :disabled="busy||['SUBMITTING','UNKNOWN'].includes(submission.state)" @click="submission=undefined">返回修改</button><button type="button" class="primary" :disabled="busy" @click="submit">确认保存配置</button></div></div>
  </form>
</template>
