<script setup lang="ts">
import StyledSelect from '../app-host/StyledSelect.vue'
import {computed} from 'vue'
const props=defineProps<{config:Record<string,unknown>;disabled?:boolean}>(),emit=defineEmits<{change:[value:Record<string,unknown>]}>()
const command=computed(()=>Array.isArray(props.config.command)?props.config.command as string[]:[]),environment=computed(()=>Object.entries(props.config.environment as Record<string,string>||{}))
function field(key:string,value:unknown){emit('change',{...props.config,[key]:value})}
function argument(index:number,value:string){const next=[...command.value];next[index]=value;field('command',next)}
function variable(index:number,key:string,value:string){const next=environment.value.map(([name,value])=>[name,value]);next[index]=[key,value];field('environment',Object.fromEntries(next))}
function mode(value:string){emit('change',{...props.config,mode:value,...value==='container'?{directory:'/workspace',uid:props.config.uid||1000,gid:props.config.gid||1000}:{}})}
</script>
<template>
  <fieldset class="instance-config-fields" :disabled="disabled"><legend>运行配置</legend>
    <label>运行模式<StyledSelect :value="String(config.mode||'')" @change="mode(($event.target as HTMLSelectElement).value)"><option value="native">可信原生程序（需要主机权限）</option><option value="container">隔离容器</option></StyledSelect></label>
    <label>工作目录<input :value="config.directory||''" :readonly="config.mode==='container'" @input="field('directory',($event.target as HTMLInputElement).value)"></label>
    <label v-if="config.mode==='container'">容器镜像<input :value="config.image||''" required @input="field('image',($event.target as HTMLInputElement).value)"></label>
    <div v-for="(arg,index) in command" :key="index" class="config-argument"><label>{{index===0?'可执行程序':`参数 ${index}`}}<textarea :value="arg" :aria-label="index===0?'可执行程序':`启动参数 ${index}`" rows="2" :required="index===0" @input="argument(index,($event.target as HTMLTextAreaElement).value)"></textarea></label><button v-if="index>0" type="button" @click="field('command',command.filter((_,i)=>i!==index))">删除参数 {{index}}</button></div>
    <button type="button" :disabled="command.length>=128" @click="field('command',[...command,''])">添加启动参数</button><p class="muted">每项原样传给程序，包含空格或换行的参数也保持一项；不会自动拼接为 Shell 命令。</p>
    <h4>环境变量</h4><div v-for="([key,value],index) in environment" :key="index" class="config-environment"><input :value="key" :aria-label="`环境变量名称 ${index+1}`" @input="variable(index,($event.target as HTMLInputElement).value,value)"><input :value="value" :aria-label="`环境变量值 ${index+1}`" @input="variable(index,key,($event.target as HTMLInputElement).value)"><button type="button" @click="field('environment',Object.fromEntries(environment.filter((_,i)=>i!==index)))">删除变量</button></div><button type="button" :disabled="environment.length>=128||environment.some(([key])=>!key)" @click="field('environment',{...config.environment as object,'':''})">添加环境变量</button><p class="muted">这些配置字段会随草稿恢复。凭据请通过节点上的受保护文件提供。</p>
    <div class="config-number-grid"><label>UID<input type="number" min="1" :required="config.mode==='container'" :value="config.uid" @input="field('uid',($event.target as HTMLInputElement).value?Number(($event.target as HTMLInputElement).value):undefined)"></label><label>GID<input type="number" min="1" :required="config.mode==='container'" :value="config.gid" @input="field('gid',($event.target as HTMLInputElement).value?Number(($event.target as HTMLInputElement).value):undefined)"></label><label>内存限制（字节，0 不限制）<input type="number" min="0" :value="config.memoryBytes||0" @input="field('memoryBytes',Number(($event.target as HTMLInputElement).value))"></label><label>CPU 配额（100000 = 1 核）<input type="number" min="0" :value="config.cpuQuota||0" @input="field('cpuQuota',Number(($event.target as HTMLInputElement).value))"></label><label>进程数上限（0 不限制）<input type="number" min="0" max="1048576" :value="config.pidsLimit||0" @input="field('pidsLimit',Number(($event.target as HTMLInputElement).value))"></label></div>
    <h4>停止与自动启动</h4><label>正常停止前输入（按原文发送）<textarea :value="String(config.stopInput||'')" aria-label="正常停止输入" rows="2" @input="field('stopInput',($event.target as HTMLTextAreaElement).value)"></textarea></label><div class="config-number-grid"><label>正常停止期限（秒）<input type="number" min="1" max="600" :value="config.stopSeconds||30" @input="field('stopSeconds',Number(($event.target as HTMLInputElement).value))"></label><label>强制结束期限（秒）<input type="number" min="1" max="120" :value="config.killSeconds||10" @input="field('killSeconds',Number(($event.target as HTMLInputElement).value))"></label></div><label class="check-row"><input type="checkbox" :checked="!!config.escalate" @change="field('escalate',($event.target as HTMLInputElement).checked)">正常停止超时后允许强制结束</label><label class="check-row"><input type="checkbox" :checked="!!config.autostart" @change="field('autostart',($event.target as HTMLInputElement).checked)">下次 Daemon 进程启动时自动启动（届时重新校验权限）</label>
  </fieldset>
</template>
