<script setup lang="ts">
import {computed,ref} from 'vue'
import {useQuery,useQueryClient} from '@tanstack/vue-query'
import {api,session,type Node} from '../services/api'
import {useDesktop} from '../desktop/store'
import {copy,json} from '../recovery/state'
import CoreUpdates from './CoreUpdates.vue'
interface Configuration {nodeId:string;name:string;group:string;tags:string;maintenance:boolean;quota:number;revision:number;requestId:string}
interface RotationTarget {nodeId:string;name:string;requestId:string}
const props=defineProps<{viewTabId:string;visible?:boolean}>(),desktop=useDesktop(),recovery=desktop.recovery!,query=useQueryClient(),error=ref(''),notice=ref(''),busy=ref(false),updateNode=ref('')
const view=computed(()=>recovery.state.views[props.viewTabId]!)
function patch(key:string,value:unknown){if(recovery.state.views[props.viewTabId])recovery.commit([{kind:'set',path:['views',props.viewTabId,'state',key],value:json(value)}])}
const nodes=useQuery({queryKey:['nodes'],queryFn:()=>api<{items:Node[]}>('/nodes'),refetchInterval:5000}),instances=useQuery({queryKey:['instances'],queryFn:()=>api<{items:{instanceId:string;nodeId:string}[]}>('/instances'),refetchInterval:5000})
const search=computed({get:()=>String(view.value.state.search||''),set:value=>patch('search',value)}),visibleNodes=computed(()=>nodes.data.value?.items.filter(node=>{const needle=search.value.toLowerCase();const haystack=[node.name,node.group||'',...(node.tags||[])].join(' ').toLowerCase();return(!view.value.resourceRef||node.nodeId===view.value.resourceRef.id)&&haystack.includes(needle)})||[])
const configuration=computed<Configuration|undefined>({get:()=>view.value.state.configuration as unknown as Configuration|undefined,set:value=>patch('configuration',value||null)}),enrollOpen=computed({get:()=>!!view.value.state.enrollOpen,set:value=>patch('enrollOpen',value)}),enrollName=computed({get:()=>String(view.value.state.enrollName||''),set:value=>patch('enrollName',value)}),enrollRequestId=computed<string|undefined>({get:()=>String(view.value.state.enrollRequestId||'')||undefined,set:value=>patch('enrollRequestId',value||null)}),rotationTarget=computed<RotationTarget|undefined>({get:()=>view.value.state.rotationTarget as unknown as RotationTarget|undefined,set:value=>patch('rotationTarget',value||null)}),revokeRequestIds=computed<Record<string,string>>({get:()=>((view.value.state.revokeRequestIds||{}) as Record<string,string>),set:value=>patch('revokeRequestIds',value)})
function configure(node:Node){configuration.value={nodeId:node.nodeId,name:node.name,group:node.group||'',tags:(node.tags||[]).join(', '),maintenance:!!node.maintenance,quota:node.quota??100,revision:node.configRevision??0,requestId:crypto.randomUUID()};error.value=''}
function beginRotation(node:Node){rotationTarget.value={nodeId:node.nodeId,name:node.name,requestId:crypto.randomUUID()};error.value=''}
function field(key:'name'|'group'|'tags'|'maintenance'|'quota',value:string|boolean|number){if(configuration.value)configuration.value={...configuration.value,[key]:value}}
function parseTags(value:string){return value.split(',').map(tag=>tag.trim()).filter(Boolean)}
async function reloadConfiguration(){const id=configuration.value?.nodeId;if(!id)return;const {data}=await nodes.refetch(),current=data?.items.find(node=>node.nodeId===id);if(current)configure(current)}
async function saveConfiguration(){
  const fixed=configuration.value?copy(configuration.value):undefined;if(!fixed||busy.value)return;busy.value=true;error.value=''
  try{await api(`/nodes/${encodeURIComponent(fixed.nodeId)}`,{method:'PATCH',headers:{'Idempotency-Key':fixed.requestId},body:JSON.stringify({name:fixed.name,group:fixed.group,tags:parseTags(fixed.tags),maintenance:fixed.maintenance,quota:fixed.quota,revision:fixed.revision})});configuration.value=undefined;notice.value='节点配置已由服务器确认';await Promise.all([query.invalidateQueries({queryKey:['nodes']}),query.invalidateQueries({queryKey:['instances']})])}catch(e){error.value=String(e)}finally{busy.value=false}
}
function download(text:string,name:string,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type})),anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function enroll(){
  if(busy.value)return;busy.value=true;error.value=''
  const requestId=enrollRequestId.value||crypto.randomUUID();enrollRequestId.value=requestId
  try{const result=await api<{token:string;expiresIn:number}>('/nodes/enrollments',{method:'POST',headers:{'Idempotency-Key':requestId},body:JSON.stringify({name:enrollName.value})});if(typeof result.token!=='string'||!result.token)throw new Error('登记服务没有返回有效票据');download(result.token,'blora-node.enrollment','text/plain');enrollRequestId.value=undefined;enrollOpen.value=false;notice.value=`登记票据已交给浏览器下载，${Math.floor(result.expiresIn/60)}分钟内供新 Daemon 的 enrollmentFile 使用。节点主动接入后才会出现在列表中。`}catch(e){error.value=String(e)}finally{busy.value=false}
}
async function rotate(){
  const fixed=rotationTarget.value?copy(rotationTarget.value):undefined;if(!fixed||busy.value)return;busy.value=true;error.value=''
  try{const result=await api<{nodeId:string;ticket:string;expiresIn:number}>(`/nodes/${encodeURIComponent(fixed.nodeId)}/rotation`,{method:'POST',headers:{'Idempotency-Key':fixed.requestId},body:JSON.stringify({reactivate:false})});if(result.nodeId!==fixed.nodeId||!result.ticket)throw new Error('换钥票据的节点身份不匹配');download(JSON.stringify({nodeId:result.nodeId,ticket:result.ticket}),'blora-node-rotation.json');rotationTarget.value=undefined;notice.value=`换钥票据已交给浏览器下载，${Math.floor(result.expiresIn/60)}分钟内供目标 Daemon 的 rotationFile 使用。重启 Daemon 完成换钥后刷新连接代次。`}catch(e){error.value=String(e)}finally{busy.value=false}
}
async function revoke(node:Node){
  if(busy.value||!window.confirm(`确认撤销节点“${node.name}”的管理身份？现有实例和资源记录会保留，节点需换钥后才能重新接入。`))return
  busy.value=true;error.value='';const requestId=revokeRequestIds.value[node.nodeId]||crypto.randomUUID();if(!revokeRequestIds.value[node.nodeId])revokeRequestIds.value={...revokeRequestIds.value,[node.nodeId]:requestId}
  try{await api<{revoked:boolean}>(`/nodes/${encodeURIComponent(node.nodeId)}/revoke`,{method:'POST',headers:{'Idempotency-Key':requestId}});const next={...revokeRequestIds.value};delete next[node.nodeId];revokeRequestIds.value=next;if(configuration.value?.nodeId===node.nodeId)configuration.value=undefined;if(rotationTarget.value?.nodeId===node.nodeId)rotationTarget.value=undefined;notice.value=`节点 ${node.name} 已撤销，旧连接已失效；完成换钥后可重新接入。`;await Promise.all([query.invalidateQueries({queryKey:['nodes']}),query.invalidateQueries({queryKey:['instances']})])}catch(e){error.value=String(e)}finally{busy.value=false}
}
</script>
<template>
  <div class="application nodes-app">
    <header class="app-heading"><div><span class="eyebrow">NODES</span><h2>节点管理</h2><p>主动连接的管理节点与实际能力。</p></div><div class="action-row"><button @click="nodes.refetch()">↻ 刷新</button><button v-if="session.user?.admin" class="primary" @click="enrollOpen=true">登记新节点</button></div></header>
    <div class="filterbar"><input v-model="search" aria-label="搜索节点" placeholder="搜索节点名称、分组或标签"></div><p v-if="nodes.error.value||error" class="error notice" role="alert">{{error||nodes.error.value?.message}}</p><p v-if="notice" class="notice" role="status">{{notice}}</p>
    <article v-for="node in visibleNodes" :key="node.nodeId" class="node-card" :data-node-id="node.nodeId"><header><span class="node-glyph">⬡</span><div><h3>{{node.name}}</h3><small>{{node.platform}} · {{node.nodeId}}</small></div><span class="status-chip" :data-status="node.state">{{node.state}}</span></header><p class="muted">最后联系 {{node.lastSeen?new Date(node.lastSeen).toLocaleString():'尚无记录'}}</p><p v-if="node.group||node.tags?.length" class="muted">分组：{{node.group||'未分组'}} · 标签：{{node.tags?.join('、')||'无'}}</p><p class="capabilities">{{Object.entries(node.capabilities || {}).map(([key,value])=>key+': '+value).join(' · ') || '尚未上报能力'}}</p><dl class="node-facts"><dt>实例 / 配额</dt><dd>{{instances.data.value?.items.filter(instance=>instance.nodeId===node.nodeId).length??'—'}} / {{node.quota??'—'}}</dd><dt>维护模式</dt><dd>{{node.maintenance?'已开启':'未开启'}}</dd><dt>配置版本</dt><dd>{{node.configRevision??'—'}}</dd><dt>连接代次</dt><dd>{{node.generation}}</dd></dl><p v-if="node.maintenance" class="warning">维护期间拒绝创建、启动和重启；已有运行保持原状态，停止仍可执行。</p><div class="action-row"><button @click="desktop.open({appId:'blora.instances',disposition:'new-window',state:{nodeFilter:node.nodeId},title:node.name+' · 实例'})">查看实例</button><button @click="desktop.open({appId:'blora.nodes',resourceRef:{kind:'node',id:node.nodeId},title:node.name,disposition:'dedicated'})">专用节点窗口</button><template v-if="session.user?.admin"><button :disabled="!['ONLINE','MAINTENANCE'].includes(node.state)" @click="updateNode=updateNode===node.nodeId?'':node.nodeId">系统更新</button><button @click="configure(node)">配置节点</button><button @click="beginRotation(node)">轮换节点密钥</button><button class="danger" @click="revoke(node)">撤销管理</button></template></div><CoreUpdates v-if="updateNode===node.nodeId&&session.user?.admin" :node-id="node.nodeId" :visible="visible!==false"/></article>
    <div v-if="!nodes.isPending.value&&!visibleNodes.length" class="empty-state"><h3>没有匹配的可见节点</h3><p>可调整筛选或登记新 Daemon，由节点主动连接并上报状态。</p></div>
    <form v-if="configuration&&session.user?.admin" class="in-window-dialog account-dialog" role="dialog" aria-label="节点配置" @submit.prevent="saveConfiguration"><h3>节点配置</h3><p>{{configuration.nodeId}} · 配置版本 {{configuration.revision}}</p><label>节点名称<input :value="configuration.name" aria-label="节点名称" required maxlength="80" @input="field('name',($event.target as HTMLInputElement).value)"></label><label>节点分组<input :value="configuration.group" aria-label="节点分组" maxlength="120" @input="field('group',($event.target as HTMLInputElement).value)"></label><label>节点标签<input :value="configuration.tags" aria-label="节点标签" placeholder="用逗号分隔，例如 prod, edge" maxlength="2600" @input="field('tags',($event.target as HTMLInputElement).value)"></label><label>实例数量配额<input :value="configuration.quota" aria-label="节点实例配额" type="number" min="1" max="10000" required @input="field('quota',Number(($event.target as HTMLInputElement).value))"></label><label class="check-row"><input :checked="configuration.maintenance" type="checkbox" @change="field('maintenance',($event.target as HTMLInputElement).checked)">维护模式</label><p class="muted">维护模式阻止新建、启动和重启，已有运行继续。标签用逗号分隔，最多32项且每项不超过80字节；提交时按配置版本校验。</p><p v-if="error" class="error" role="alert">{{error}}</p><button type="button" @click="reloadConfiguration">读取当前值并替换表单</button><div class="action-row"><button type="button" @click="configuration=undefined">返回</button><button class="primary" :disabled="busy">保存节点配置</button></div></form>
    <form v-if="enrollOpen&&session.user?.admin" class="in-window-dialog account-dialog" role="dialog" aria-label="登记新节点" @submit.prevent="enroll"><h3>登记新节点</h3><label>预设节点名称<input v-model="enrollName" aria-label="登记节点名称" required maxlength="80"></label><p>下载一次登记票据，把此文件配置到新 Daemon 的 enrollmentFile。Daemon 通过可信 Master 地址与 CA 主动建立连接。</p><p class="muted">票据有效10分钟，只通过浏览器下载交付，不进入工作现场。</p><p v-if="error" class="error" role="alert">{{error}}</p><div class="action-row"><button type="button" @click="enrollOpen=false">返回</button><button class="primary" :disabled="busy">生成并下载登记票据</button></div></form>
    <form v-if="rotationTarget&&session.user?.admin" class="in-window-dialog account-dialog" role="dialog" aria-label="节点密钥轮换" @submit.prevent="rotate"><h3>节点密钥轮换</h3><p>{{rotationTarget.name}} · {{rotationTarget.nodeId}}</p><p>下载有效10分钟的换钥票据，在此节点配置 Daemon 的 rotationFile 后重启 Daemon。节点身份和实例资源保持原引用，旧密钥与旧连接将失效。</p><p class="muted">票据仅通过此次浏览器下载交付；刷新不会重新签发。</p><p v-if="error" class="error" role="alert">{{error}}</p><div class="action-row"><button type="button" @click="rotationTarget=undefined">返回</button><button class="primary" :disabled="busy">生成并下载换钥票据</button></div></form>
  </div>
</template>
