<script setup lang="ts">
import {computed,onBeforeUnmount,ref,watch} from 'vue'
import {useQuery,useQueryClient} from '@tanstack/vue-query'
import {useDesktop} from '../desktop/store'
import {api,session,type Audit,type User,type Instance,type Node} from '../services/api'
import {copy,json} from '../recovery/state'
import {nodeActions,passwordProblem,permissionLabels,type Grant,type RoleTemplate} from '../services/accounts'
import type {ResourceRef} from '../app-host/types'
import PasswordForm from './PasswordForm.vue'
interface UserEdit {userId:string;name:string;admin:boolean;disabled:boolean;revision:number;requestId:string}
interface Authorization {userId:string;resource:ResourceRef;actions:string[];requestId:string;revoke:boolean;roleId?:string;roleName?:string;revision?:number}
const props=defineProps<{viewTabId:string;visible:boolean}>(),desktop=useDesktop(),recovery=desktop.recovery!,query=useQueryClient(),error=ref(''),notice=ref(''),busy=ref(false)
const view=computed(()=>recovery.state.views[props.viewTabId]!),allowed=computed(()=>!!session.user?.admin)
function patch(key:string,value:unknown){if(recovery.state.views[props.viewTabId])recovery.commit([{kind:'set',path:['views',props.viewTabId,'state',key],value:json(value)}])}
const search=computed({get:()=>String(view.value.state.search||''),set:value=>patch('search',value)}),selectedId=computed({get:()=>String(view.value.state.userId||view.value.resourceRef?.id||''),set:value=>patch('userId',value)})
const users=useQuery({queryKey:['users'],enabled:allowed,queryFn:()=>api<{items:User[]}>('/users'),refetchInterval:5000}),roles=useQuery({queryKey:['roles'],enabled:allowed,queryFn:()=>api<{items:RoleTemplate[];semantics:string}>('/roles')}),grants=useQuery({queryKey:['grants'],enabled:allowed,queryFn:()=>api<{items:Grant[]}>('/grants'),refetchInterval:5000})
const nodes=useQuery({queryKey:['nodes'],enabled:allowed,queryFn:()=>api<{items:Node[]}>('/nodes')}),instances=useQuery({queryKey:['instances'],enabled:allowed,queryFn:()=>api<{items:Instance[]}>('/instances')})
const auditUser=computed({get:()=>String(view.value.state.auditUser||''),set:value=>patch('auditUser',value)}),auditNode=computed({get:()=>String(view.value.state.auditNode||''),set:value=>patch('auditNode',value)}),auditResource=computed({get:()=>String(view.value.state.auditResource||''),set:value=>patch('auditResource',value)}),auditAction=computed({get:()=>String(view.value.state.auditAction||''),set:value=>patch('auditAction',value)}),auditFrom=computed({get:()=>String(view.value.state.auditFrom||''),set:value=>patch('auditFrom',value)}),auditTo=computed({get:()=>String(view.value.state.auditTo||''),set:value=>patch('auditTo',value)})
const auditPath=computed(()=>{const params=new URLSearchParams({limit:'100'});if(auditUser.value)params.set('userId',auditUser.value);if(auditNode.value)params.set('nodeId',auditNode.value);if(auditResource.value)params.set('resource',auditResource.value);if(auditAction.value)params.set('action',auditAction.value);if(auditFrom.value){const date=new Date(auditFrom.value);if(!Number.isNaN(date.getTime()))params.set('from',date.toISOString())}if(auditTo.value){const date=new Date(auditTo.value);if(!Number.isNaN(date.getTime()))params.set('to',date.toISOString())}return `/audit?${params}`})
const audit=useQuery({queryKey:['audit'],enabled:allowed,queryFn:()=>api<{items:Audit[];nextOffset:number}>(auditPath.value)})
const filtered=computed(()=>users.data.value?.items.filter(user=>user.name.toLowerCase().includes(search.value.toLowerCase()))||[]),selected=computed(()=>users.data.value?.items.find(user=>user.userId===selectedId.value)),userGrants=computed(()=>grants.data.value?.items.filter(grant=>grant.userId===selectedId.value)||[])
const edit=computed<UserEdit|undefined>({get:()=>view.value.state.userEdit as unknown as UserEdit|undefined,set:value=>patch('userEdit',value||null)}),roleDraft=computed<(RoleTemplate&{requestId:string})|undefined>({get:()=>view.value.state.roleDraft as unknown as (RoleTemplate&{requestId:string})|undefined,set:value=>patch('roleDraft',value||null)}),authorization=computed<Authorization|undefined>({get:()=>view.value.state.authorization as unknown as Authorization|undefined,set:value=>patch('authorization',value||null)})
const createOpen=computed({get:()=>!!view.value.state.createOpen,set:value=>patch('createOpen',value)}),newName=computed({get:()=>String(view.value.state.newName||''),set:value=>patch('newName',value)}),newAdmin=computed({get:()=>!!view.value.state.newAdmin,set:value=>patch('newAdmin',value)}),createRequestId=computed<string|undefined>({get:()=>{const value=String(view.value.state.createRequestId||'');return value||undefined},set:value=>patch('createRequestId',value||null)}),newPassword=ref(''),newConfirmation=ref('')
const resetUser=computed<User|undefined>({get:()=>view.value.state.resetUser as unknown as User|undefined,set:value=>patch('resetUser',value||null)})
const scopeKind=computed({get:()=>String(view.value.state.scopeKind||'instance'),set:value=>{patch('scopeKind',value);patch('scopeId','')}}),scopeId=computed({get:()=>String(view.value.state.scopeId||''),set:value=>patch('scopeId',value)}),roleId=computed({get:()=>String(view.value.state.roleId||'reader'),set:value=>patch('roleId',value)}),action=computed({get:()=>String(view.value.state.action||'instance.read'),set:value=>patch('action',value)})
const scopeOptions=computed(()=>scopeKind.value==='node'?nodes.data.value?.items.map(node=>({id:node.nodeId,title:node.name}))||[]:instances.data.value?.items.map(instance=>({id:instance.instanceId,title:`${instance.name} · ${instance.nodeName||instance.nodeId}`}))||[]),chosenRole=computed(()=>roles.data.value?.items.find(role=>role.roleId===roleId.value)),availableActions=computed(()=>Object.entries(permissionLabels).filter(([action])=>scopeKind.value==='node'||!nodeActions.has(action)))
function scope():ResourceRef|undefined{if(!scopeOptions.value.some(option=>option.id===scopeId.value))return;return{kind:scopeKind.value,id:scopeId.value,nodeId:scopeKind.value==='instance'?instances.data.value?.items.find(item=>item.instanceId===scopeId.value)?.nodeId:undefined}}
function resourceTitle(ref:ResourceRef){return ref.kind==='node'?nodes.data.value?.items.find(node=>node.nodeId===ref.id)?.name||ref.id:instances.data.value?.items.find(instance=>instance.instanceId===ref.id)?.name||ref.id}
function clearSecrets(){newPassword.value='';newConfirmation.value=''}
watch(()=>props.visible,visible=>{if(!visible)clearSecrets()});watch(createOpen,open=>{if(!open)clearSecrets()});watch([auditUser,auditNode,auditResource,auditAction,auditFrom,auditTo],()=>{if(allowed.value)audit.refetch()});onBeforeUnmount(clearSecrets)
async function refresh(){await Promise.all([users.refetch(),roles.refetch(),grants.refetch(),audit.refetch()])}
function auditTime(value:string){return new Date(value).toLocaleString()}
async function createUser(){
  error.value=passwordProblem(newPassword.value,newConfirmation.value);if(error.value||busy.value)return;busy.value=true;notice.value='';const requestId=createRequestId.value||crypto.randomUUID();if(!createRequestId.value)createRequestId.value=requestId
  try{const {user}=await api<{user:User}>('/users',{method:'POST',headers:{'Idempotency-Key':requestId},body:JSON.stringify({name:newName.value,admin:newAdmin.value,password:newPassword.value})});createRequestId.value=undefined;selectedId.value=user.userId;createOpen.value=false;patch('newName','');patch('newAdmin',false);notice.value='账号已创建';await users.refetch()}catch(e){error.value=String(e)}finally{clearSecrets();busy.value=false}
}
function openCreate(){createOpen.value=true;if(!createRequestId.value)createRequestId.value=crypto.randomUUID()}
function closeCreate(){createOpen.value=false;createRequestId.value=undefined;patch('newName','');patch('newAdmin',false);clearSecrets()}
function editUser(user:User){edit.value={...copy(user),requestId:crypto.randomUUID()};error.value=''}
function editField(key:'name'|'admin'|'disabled',value:string|boolean){if(edit.value)edit.value={...edit.value,[key]:value}}
async function saveUser(){const fixed=edit.value?copy(edit.value):undefined;if(!fixed||busy.value)return;busy.value=true;error.value='';try{await api(`/users/${encodeURIComponent(fixed.userId)}`,{method:'PATCH',headers:{'Idempotency-Key':fixed.requestId},body:JSON.stringify({name:fixed.name,admin:fixed.admin,disabled:fixed.disabled,revision:fixed.revision})});edit.value=undefined;if(session.user?.userId===fixed.userId){session.error='账号资料已更新，请重新登录。';session.user=undefined}else{notice.value='账号资料已更新，该账号的原会话已撤销';await users.refetch()}}catch(e){error.value=String(e)}finally{busy.value=false}}
function editRole(role?:RoleTemplate){roleDraft.value=role&&!role.builtin?{...copy(role),requestId:crypto.randomUUID()}:{roleId:`custom-${crypto.randomUUID()}`,name:role?role.name+' 副本':'',actions:role?[...role.actions]:['instance.read'],nodeOnly:role?.nodeOnly||false,builtin:false,revision:0,requestId:crypto.randomUUID()};error.value=''}
function roleField(key:'name'|'nodeOnly',value:string|boolean){if(roleDraft.value)roleDraft.value={...roleDraft.value,[key]:value}}
function toggleAction(action:string){const draft=roleDraft.value;if(!draft)return;const actions=draft.actions.includes(action)?draft.actions.filter(value=>value!==action):[...draft.actions,action];roleDraft.value={...draft,actions,nodeOnly:draft.nodeOnly||actions.some(action=>nodeActions.has(action))}}
async function saveRole(){const fixed=roleDraft.value?copy(roleDraft.value):undefined;if(!fixed||busy.value)return;busy.value=true;error.value='';try{await api(`/roles/${encodeURIComponent(fixed.roleId)}`,{method:'PUT',headers:{'Idempotency-Key':fixed.requestId},body:JSON.stringify({name:fixed.name,actions:fixed.actions,nodeOnly:fixed.nodeOnly,revision:fixed.revision})});roleDraft.value=undefined;notice.value='模板已保存。已有显式授权保持原样，需选择资源后明确应用此版本。';await roles.refetch()}catch(e){error.value=String(e)}finally{busy.value=false}}
function prepareRole(revoke=false){const resource=scope(),role=chosenRole.value;if(!selected.value||!resource||!role)return;if(role.nodeOnly&&resource.kind!=='node'){error.value='此模板只适用于节点范围';return}authorization.value={userId:selected.value.userId,resource,roleId:role.roleId,roleName:role.name,actions:[...role.actions],revision:role.revision,revoke,requestId:crypto.randomUUID()}}
function prepareGrant(existing?:Grant){const resource=existing?.resource||scope(),userId=existing?.userId||selected.value?.userId;if(!resource||!userId)return;authorization.value={userId,resource,actions:[existing?.action||action.value],revoke:!!existing,requestId:crypto.randomUUID()}}
async function applyAuthorization(){const fixed=authorization.value?copy(authorization.value):undefined;if(!fixed||busy.value)return;busy.value=true;error.value='';try{if(fixed.roleId)await api(`/roles/${encodeURIComponent(fixed.roleId)}/apply`,{method:'POST',headers:{'Idempotency-Key':fixed.requestId},body:JSON.stringify({userId:fixed.userId,resource:fixed.resource,revision:fixed.revision,revoke:fixed.revoke})});else await api('/grants',{method:fixed.revoke?'DELETE':'POST',headers:{'Idempotency-Key':fixed.requestId},body:JSON.stringify({userId:fixed.userId,resource:fixed.resource,action:fixed.actions[0]})});authorization.value=undefined;notice.value='显式授权已更新，相关实时连接已撤销并需重新鉴权';await query.invalidateQueries({queryKey:['grants']})}catch(e){error.value=String(e)}finally{busy.value=false}}
</script>
<template>
  <div class="application users-app">
    <header class="app-heading"><div><span class="eyebrow">USERS & PERMISSIONS</span><h2>用户与权限</h2><p>按账号和具体资源管理显式授权。</p></div><button v-if="allowed" class="primary" @click="openCreate">创建账号</button></header>
    <div v-if="!allowed" class="empty-state">需要平台管理员权限。</div>
    <template v-else>
      <p v-if="users.error.value||roles.error.value||grants.error.value||audit.error.value||error" class="error notice" role="alert">{{error||users.error.value?.message||roles.error.value?.message||grants.error.value?.message||audit.error.value?.message}}</p><p v-if="notice" class="notice" role="status">{{notice}}</p>
      <div class="filterbar"><input v-model="search" aria-label="搜索账号" placeholder="搜索账号"><button @click="refresh">刷新账号和授权</button></div>
      <div class="users-columns"><section class="users-list"><h3>账号</h3><article v-for="user in filtered" :key="user.userId" class="user-card" :class="{selected:selectedId===user.userId}"><button class="user-select" @click="selectedId=user.userId">{{user.name}}<small>{{user.disabled?'已禁用':user.admin?'平台管理员':'成员'}}</small></button><div><button @click="editUser(user)">编辑 {{user.name}}</button><button @click="resetUser=copy(user)">重置密码 {{user.name}}</button></div></article></section>
      <section v-if="selected" class="user-grants"><h3>{{selected.name}} 的显式授权</h3><p class="muted">{{selected.admin?'平台管理员拥有平台管理能力。':'节点范围的动作适用于该节点下的实例；查看、创建与控制分别授权。'}}</p><div class="grant-row" v-for="grant in userGrants" :key="grant.resource.kind+grant.resource.id+grant.action"><span>{{resourceTitle(grant.resource)}} · {{grant.resource.kind}}</span><span>{{permissionLabels[grant.action]||grant.action}}</span><button @click="prepareGrant(grant)">撤销此授权</button></div><p v-if="!userGrants.length" class="muted">没有显式资源授权。</p>
        <div class="grant-editor"><label>资源范围<select v-model="scopeKind" aria-label="授权资源类型"><option value="instance">实例</option><option value="node">节点</option></select></label><label>目标资源<select v-model="scopeId" aria-label="授权目标资源"><option value="">选择资源</option><option v-for="option in scopeOptions" :key="option.id" :value="option.id">{{option.title}}</option></select></label><label>角色模板<select v-model="roleId" aria-label="授权角色模板"><option v-for="role in roles.data.value?.items" :key="role.roleId" :value="role.roleId">{{role.name}}{{role.nodeOnly?' · 仅节点':''}}</option></select></label><p class="muted">模板会展开为显式动作；之后修改模板不会追改既有授权。撤销模板会删除它列出的匹配授权。</p><div class="action-row"><button :disabled="!scopeId" @click="prepareRole()">预览模板授权</button><button :disabled="!scopeId" @click="prepareRole(true)">预览模板撤销</button></div><label>单独动作<select v-model="action" aria-label="单独授权动作"><option v-for="[key,label] in availableActions" :key="key" :value="key">{{label}}</option></select></label><button :disabled="!scopeId" @click="prepareGrant()">预览单独授权</button></div>
      </section><section v-else class="empty-state">选择账号以查看资源授权。</section></div>
      <section class="role-templates"><div class="action-row"><h3>角色模板</h3><button @click="editRole()">创建自定义模板</button></div><article v-for="role in roles.data.value?.items" :key="role.roleId" class="role-card"><strong>{{role.name}}</strong><small>{{role.builtin?'内置模板':'自定义'}} · 版本 {{role.revision}}{{role.nodeOnly?' · 仅节点':''}}</small><p>{{role.actions.map(action=>permissionLabels[action]||action).join('、')}}</p><button @click="editRole(role)">{{role.builtin?'复制为自定义模板':'编辑模板'}}</button></article></section>
      <section class="audit-log"><div class="action-row"><div><h3>操作审计</h3><p class="muted">按用户、节点、资源、动作和时间检索最近的管理记录。</p></div><button @click="audit.refetch()">刷新审计</button></div><div class="filterbar audit-filters"><select v-model="auditUser" aria-label="审计用户"><option value="">全部用户</option><option v-for="user in users.data.value?.items" :key="user.userId" :value="user.userId">{{user.name}}</option></select><select v-model="auditNode" aria-label="审计节点"><option value="">全部节点</option><option v-for="node in nodes.data.value?.items" :key="node.nodeId" :value="node.nodeId">{{node.name}}</option></select><input v-model="auditResource" aria-label="审计资源" placeholder="资源，例如 node:..."><input v-model="auditAction" aria-label="审计动作" placeholder="动作，例如 node.settings"><label>从 <input v-model="auditFrom" aria-label="审计起始时间" type="datetime-local"></label><label>到 <input v-model="auditTo" aria-label="审计结束时间" type="datetime-local"></label></div><div v-if="audit.isPending.value" class="empty-state">正在读取审计记录…</div><div v-else-if="!audit.data.value?.items.length" class="empty-state">没有符合条件的审计记录。</div><div v-else class="audit-rows"><article v-for="item in audit.data.value.items" :key="item.sequence" class="audit-row"><time :datetime="item.recordedAt">{{auditTime(item.recordedAt)}}</time><span>{{users.data.value?.items.find(user=>user.userId===item.actorId)?.name||item.actorId}}</span><span>{{item.nodeId||'平台'}}</span><span>{{item.resourceKey}}</span><strong>{{item.action}}</strong><span>{{item.result}}</span></article></div><p class="muted">最多显示最近100条；可缩小筛选范围后继续查询。</p></section>
    </template>
    <form v-if="createOpen&&allowed" class="in-window-dialog account-dialog" role="dialog" aria-label="创建账号" @submit.prevent="createUser"><h3>创建账号</h3><label>账号名称<input v-model="newName" aria-label="新账号名称" required maxlength="80"></label><label class="check-row"><input v-model="newAdmin" type="checkbox">平台管理员</label><label>初始密码<input v-model="newPassword" aria-label="初始密码" type="password" autocomplete="new-password" required></label><label>确认初始密码<input v-model="newConfirmation" aria-label="确认初始密码" type="password" autocomplete="new-password" required></label><p class="muted">密码不进入工作现场；刷新后需要重新输入。成员创建后需单独授予资源权限。</p><p v-if="error" class="error" role="alert">{{error}}</p><div class="action-row"><button type="button" @click="closeCreate">返回</button><button class="primary" :disabled="busy">确认创建账号</button></div></form>
    <form v-if="edit&&allowed" class="in-window-dialog account-dialog" role="dialog" aria-label="编辑账号" @submit.prevent="saveUser"><h3>编辑账号</h3><p>{{edit.userId}} · 版本 {{edit.revision}}</p><label>账号名称<input :value="edit.name" aria-label="编辑账号名称" required @input="editField('name',($event.target as HTMLInputElement).value)"></label><label class="check-row"><input :checked="edit.admin" type="checkbox" @change="editField('admin',($event.target as HTMLInputElement).checked)">平台管理员</label><label class="check-row"><input :checked="edit.disabled" type="checkbox" @change="editField('disabled',($event.target as HTMLInputElement).checked)">禁用账号</label><p class="muted">保存资料会撤销此账号的登录会话和实时连接。最后一个可用管理员由服务器保护。</p><p v-if="error" class="error" role="alert">{{error}}</p><div class="action-row"><button type="button" @click="edit=undefined">返回</button><button class="primary" :disabled="busy">保存账号资料</button></div></form>
    <div v-if="resetUser&&allowed" class="in-window-dialog account-dialog" role="dialog" aria-label="重置账号密码"><PasswordForm :key="resetUser.userId" :user="resetUser" :visible="visible" @changed="notice='密码已重置，该账号会话已撤销';resetUser=undefined;users.refetch()"/><button @click="resetUser=undefined">返回</button></div>
    <form v-if="roleDraft&&allowed" class="in-window-dialog account-dialog" role="dialog" aria-label="角色模板编辑" @submit.prevent="saveRole"><h3>角色模板</h3><label>模板名称<input :value="roleDraft.name" aria-label="模板名称" required @input="roleField('name',($event.target as HTMLInputElement).value)"></label><label class="check-row"><input :checked="roleDraft.nodeOnly" type="checkbox" :disabled="roleDraft.actions.some(action=>nodeActions.has(action))" @change="roleField('nodeOnly',($event.target as HTMLInputElement).checked)">仅用于节点范围</label><div class="permission-options"><label v-for="[key,label] in Object.entries(permissionLabels)" :key="key" class="check-row"><input :checked="roleDraft.actions.includes(key)" type="checkbox" @change="toggleAction(key)">{{label}}</label></div><p class="muted">保存只更新模板版本；既有授权需在具体资源上明确重新应用。</p><p v-if="error" class="error" role="alert">{{error}}</p><div class="action-row"><button type="button" @click="roleDraft=undefined">返回</button><button class="primary" :disabled="busy||!roleDraft.actions.length">保存模板</button></div></form>
    <form v-if="authorization&&allowed" class="in-window-dialog account-dialog" role="dialog" aria-label="确认资源授权" @submit.prevent="applyAuthorization"><h3>{{authorization.revoke?'撤销':'授予'}}资源权限</h3><p>账号：{{users.data.value?.items.find(user=>user.userId===authorization!.userId)?.name||authorization.userId}}</p><p>资源：{{resourceTitle(authorization.resource)}} · {{authorization.resource.id}}</p><p v-if="authorization.roleName">模板：{{authorization.roleName}} · 版本 {{authorization.revision}}</p><p>{{authorization.actions.map(action=>permissionLabels[action]||action).join('、')}}</p><p class="muted">确认后立即更新显式授权，并撤销此账号的相关实时连接。</p><p v-if="error" class="error" role="alert">{{error}}</p><div class="action-row"><button type="button" @click="authorization=undefined">返回</button><button class="primary" :disabled="busy">确认{{authorization.revoke?'撤销':'授权'}}</button></div></form>
  </div>
</template>
