import {pressEditorKey} from '../helpers/editor-key'
import {test,expect} from '@playwright/test'
// API fixtures are exclusively a browser test boundary. Production uses fetch against Master.
test.beforeEach(async({page})=>{
  await page.route('**/api/v1/**',route=>{const path=new URL(route.request().url()).pathname;return route.fulfill({json:path.endsWith('/session')?{user:{userId:'browser-test',name:'测试用户',admin:true},csrfToken:'test-only'}:{items:[]}})})
})
test('Monaco text, undo/redo and original view identity survive immediate reload and moving windows',async({page})=>{
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message))
  await page.goto('/');await page.locator('[data-app="blora.editor"]').click();await expect(page.locator('.monaco-editor')).toBeVisible()
  // Monaco uses native EditContext in Chromium. Its hidden readonly IME textarea
  // is not the editor input; focus the accessible editing surface instead.
  const editor=page.getByRole('textbox',{name:'文件正文编辑器'});await editor.focus();await page.keyboard.insertText('中文输入\nalpha');await page.keyboard.insertText('β');await pressEditorKey(page,'z')
  const original=await page.locator('[data-view-tab]').first().getAttribute('data-view-tab')
  await page.reload()
  await expect(page.locator('.monaco-editor')).toBeVisible();await expect(page.locator('.monaco-editor .view-lines')).toContainText('alpha');await expect(page.locator('.monaco-editor .view-lines')).not.toContainText('β')
  await page.getByRole('textbox',{name:'文件正文编辑器'}).focus();await pressEditorKey(page,'y');await expect(page.locator('.monaco-editor .view-lines')).toContainText('β')
  await page.locator('[aria-label^="标签菜单"]').click();await page.getByRole('button',{name:'移到新窗口',exact:true}).click();await page.reload()
  await expect(page.locator(`[data-view-tab="${original}"]`)).toHaveCount(1);await expect(page.locator('.monaco-editor .view-lines')).toContainText('β')
  await page.getByRole('textbox',{name:'文件正文编辑器'}).focus();await pressEditorKey(page,'z');await expect(page.locator('.monaco-editor .view-lines')).not.toContainText('β');expect(errors).toEqual([])
})
test('window geometry and independent form drafts survive immediate reload',async({page})=>{
  await page.goto('/');await page.locator('[data-app="blora.instances"]').click();const win=page.locator('.app-window').first(),title=win.locator('.window-titlebar');const rect=await title.boundingBox();await page.mouse.move(rect!.x+240,rect!.y+15);await page.mouse.down();await page.mouse.move(rect!.x+370,rect!.y+60,{steps:5});await page.mouse.up();const transform=await win.evaluate(el=>(el as HTMLElement).style.transform);await win.getByRole('searchbox',{name:'搜索实例'}).fill('未提交筛选');await page.reload();await expect(page.locator('.app-window')).toHaveCSS('transform',/matrix/);expect(await page.locator('.app-window').evaluate(el=>(el as HTMLElement).style.transform)).toBe(transform);await expect(page.getByRole('searchbox',{name:'搜索实例'})).toHaveValue('未提交筛选')
})

test('dragging retains full material and survives reload while Escape restores geometry',async({page})=>{
  await page.goto('/');await page.locator('[data-app="blora.instances"]').click()
  const win=page.locator('.app-window'),title=win.locator('.window-titlebar')
  const geometry=()=>win.evaluate(element=>(element as HTMLElement).style.transform)
  const material=await win.evaluate(element=>getComputedStyle(element).backdropFilter)
  expect(material).toContain('blur(')
  const begin=async()=>{
    const box=await title.boundingBox()
    await page.mouse.move(box!.x+240,box!.y+15);await page.mouse.down()
    await page.mouse.move(box!.x+300,box!.y+45,{steps:3})
    await expect(win).toHaveClass(/moving/)
  }
  const original=await geometry()
  await begin();await expect.poll(geometry).not.toBe(original)
  expect(await win.evaluate(element=>getComputedStyle(element).backdropFilter)).toBe(material)
  const moved=await geometry()
  await page.reload();await page.mouse.up()
  await expect.poll(geometry).toBe(moved)
  await begin();await expect.poll(geometry).not.toBe(moved)
  await page.keyboard.press('Escape');await page.mouse.up()
  await expect.poll(geometry).toBe(moved)
  await page.reload();await expect.poll(geometry).toBe(moved)
})

test('theme palette and translucency remain independent across all four combinations and reload',async({page})=>{
  await page.goto('/')
  const root=page.locator('html')
  await expect(root).toHaveAttribute('data-translucency','on')
  await expect(root).toHaveAttribute('data-palette','ice')
  const appIcon=page.locator('.desktop-icon .application-art').first()
  await expect(appIcon).toHaveAttribute('data-icon-style','h04-spectrum-silver')
  const artwork=await appIcon.locator('image').getAttribute('href')
  await page.locator('.dock-item[aria-label="设置"]').click()
  const toggle=page.getByRole('switch',{name:'通透模式'})
  const palette=page.getByRole('combobox',{name:'主题配色'})
  const appearance=()=>page.evaluate(()=>({
    primary:getComputedStyle(document.documentElement).getPropertyValue('--primary').trim(),
    wallpaper:getComputedStyle(document.querySelector('.desktop')!).backgroundImage,
    material:getComputedStyle(document.querySelector('.topbar')!).backdropFilter,
  }))
  await expect(toggle).toBeChecked()
  await expect(palette).toHaveValue('ice')
  const blueGlass=await appearance()
  expect(blueGlass.wallpaper).toContain('data:image/svg+xml')
  expect(blueGlass.material).toContain('blur(')
  await toggle.uncheck()
  await expect(root).toHaveAttribute('data-translucency','off')
  await expect(root).toHaveAttribute('data-palette','ice')
  const blueSolid=await appearance()
  expect(blueSolid.primary).toBe(blueGlass.primary)
  expect(blueSolid.wallpaper).toBe(blueGlass.wallpaper)
  expect(blueSolid.material).toBe('none')
  await expect(appIcon).toHaveAttribute('data-icon-style','h04-spectrum-silver')
  await expect(appIcon.locator('image')).toHaveAttribute('href',artwork!)
  await page.reload()
  await expect(toggle).not.toBeChecked()
  await expect(palette).toHaveValue('ice')
  await expect(root).toHaveAttribute('data-translucency','off')
  expect((await appearance()).wallpaper).toBe(blueGlass.wallpaper)
  await palette.selectOption('mineral')
  await expect(root).toHaveAttribute('data-palette','mineral')
  await expect(root).toHaveAttribute('data-translucency','off')
  const mineralSolid=await appearance()
  expect(mineralSolid.primary).not.toBe(blueGlass.primary)
  expect(mineralSolid.wallpaper).toContain('/wallpaper.svg')
  expect(mineralSolid.material).toBe('none')
  await toggle.check()
  await expect(root).toHaveAttribute('data-translucency','on')
  await expect(root).toHaveAttribute('data-palette','mineral')
  const mineralGlass=await appearance()
  expect(mineralGlass.primary).toBe(mineralSolid.primary)
  expect(mineralGlass.wallpaper).toBe(mineralSolid.wallpaper)
  expect(mineralGlass.material).toContain('blur(')
  await page.reload()
  await expect(toggle).toBeChecked()
  await expect(palette).toHaveValue('mineral')
  await expect(root).toHaveAttribute('data-palette','mineral')
  await expect(root).toHaveAttribute('data-translucency','on')
  await expect(appIcon).toHaveAttribute('data-icon-style','h04-spectrum-silver')
  await expect(appIcon.locator('image')).toHaveAttribute('href',artwork!)
  expect((await appearance()).wallpaper).toBe(mineralSolid.wallpaper)
})

test('additional colour themes keep their own colours and wallpapers when material changes',async({page})=>{
  await page.goto('/')
  await page.locator('.dock-item[aria-label="设置"]').click()
  const root=page.locator('html')
  const palette=page.getByRole('combobox',{name:'主题配色'})
  const toggle=page.getByRole('switch',{name:'通透模式'})
  const icon=page.locator('.desktop-icon .application-art image').first()
  const artwork=await icon.getAttribute('href')
  const colours=new Set<string>(),wallpapers=new Set<string>()
  const appearance=()=>page.evaluate(()=>({
    primary:getComputedStyle(document.documentElement).getPropertyValue('--primary').trim(),
    wallpaper:getComputedStyle(document.querySelector('.desktop')!).backgroundImage,
    material:getComputedStyle(document.querySelector('.topbar')!).backdropFilter,
  }))
  for(const id of ['sand','sage','iris','rose']){
    await palette.selectOption(id)
    await expect(root).toHaveAttribute('data-palette',id)
    await expect(toggle).toBeChecked()
    const glass=await appearance()
    expect(glass.material).toContain('blur(')
    colours.add(glass.primary);wallpapers.add(glass.wallpaper)
    await toggle.uncheck()
    await expect(root).toHaveAttribute('data-translucency','off')
    const solid=await appearance()
    expect(solid.primary).toBe(glass.primary)
    expect(solid.wallpaper).toBe(glass.wallpaper)
    expect(solid.material).toBe('none')
    await expect(icon).toHaveAttribute('href',artwork!)
    await toggle.check()
  }
  expect(colours.size).toBe(4)
  expect(wallpapers.size).toBe(4)
  await page.reload()
  await expect(palette).toHaveValue('rose')
  await expect(toggle).toBeChecked()
  await expect(root).toHaveAttribute('data-palette','rose')
})

test('dark theme updates app artwork and an open editor while palette and material stay independent',async({page})=>{
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message))
  await page.goto('/')
  const root=page.locator('html'),icon=page.locator('.desktop-icon .application-art image').first()
  const lightArtwork=await icon.getAttribute('href')
  await page.locator('[data-app="blora.editor"]').click()
  await expect(page.locator('.monaco-editor.vs')).toBeVisible()
  await page.locator('.dock-item[aria-label="设置"]').click()
  const settings=page.locator('.settings-panel')
  await settings.locator('label').filter({hasText:/^主题(?!配色)/}).locator('select').selectOption('dark')
  await expect(root).toHaveAttribute('data-theme','dark')
  await expect(page.locator('.monaco-editor.vs-dark')).toHaveCount(1)
  const darkArtwork=await icon.getAttribute('href')
  expect(darkArtwork).not.toBe(lightArtwork)
  expect(darkArtwork).toContain('h04-spectrum-night-clear-forms')
  await page.getByRole('combobox',{name:'主题配色'}).selectOption('rose')
  await page.getByRole('switch',{name:'通透模式'}).uncheck()
  await expect(root).toHaveAttribute('data-palette','rose')
  await expect(root).toHaveAttribute('data-translucency','off')
  await expect(icon).toHaveAttribute('href',darkArtwork!)
  await page.reload()
  await expect(root).toHaveAttribute('data-theme','dark')
  await expect(root).toHaveAttribute('data-palette','rose')
  await expect(icon).toHaveAttribute('href',darkArtwork!)
  await expect(page.locator('.monaco-editor.vs-dark')).toHaveCount(1)
  await settings.locator('label').filter({hasText:/^主题(?!配色)/}).locator('select').selectOption('light')
  await expect(root).toHaveAttribute('data-theme','light')
  await expect(icon).toHaveAttribute('href',lightArtwork!)
  await expect(page.locator('.monaco-editor.vs')).toHaveCount(1)
  expect(errors).toEqual([])
})

test('dark palette wallpapers keep their shapes and custom wallpaper overrides mineral',async({page})=>{
  await page.goto('/')
  await page.locator('.dock-item[aria-label="设置"]').click()
  const root=page.locator('html')
  await page.locator('.settings-panel label').filter({hasText:/^主题(?!配色)/}).locator('select').selectOption('dark')
  const palette=page.getByRole('combobox',{name:'主题配色'})
  const wallpaper=page.getByRole('combobox',{name:'壁纸风格'})
  const material=page.getByRole('switch',{name:'通透模式'})
  const background=()=>page.locator('.desktop').evaluate(element=>getComputedStyle(element).backgroundImage)
  const darkWallpapers=new Set<string>()
  for(const value of ['ice','mineral','sand','sage','iris','rose']){
    await palette.selectOption(value)
    const artwork=await background()
    expect(artwork).not.toContain('linear-gradient(')
    darkWallpapers.add(artwork)
  }
  expect(darkWallpapers.size).toBe(6)
  await palette.selectOption('sand')
  const sand=await background()
  await material.uncheck()
  expect(await background()).toBe(sand)
  await material.check()
  expect(await background()).toBe(sand)
  await palette.selectOption('mineral')
  const mineral=await background()
  await wallpaper.selectOption('photo')
  await expect(root).toHaveAttribute('data-wallpaper-choice','photo')
  expect(await background()).not.toBe(mineral)
  await page.reload()
  await expect(root).toHaveAttribute('data-theme','dark')
  await expect(root).toHaveAttribute('data-palette','mineral')
  expect(await background()).not.toBe(mineral)
  await expect(page.locator('.desktop-icon .application-art image').first()).toHaveAttribute('href',/h04-spectrum-night-clear-forms/)
})

test('wallpaper styles are distinct and stay independent of palette, material and application icons',async({page})=>{
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message))
  await page.goto('/')
  await page.locator('.dock-item[aria-label="设置"]').click()
  const root=page.locator('html')
  const wallpaper=page.getByRole('combobox',{name:'壁纸风格'})
  const palette=page.getByRole('combobox',{name:'主题配色'})
  const material=page.getByRole('switch',{name:'通透模式'})
  const icon=page.locator('.desktop-icon .application-art image').first()
  const artwork=await icon.getAttribute('href')
  const appearance=()=>page.evaluate(()=>({
    primary:getComputedStyle(document.documentElement).getPropertyValue('--primary').trim(),
    background:getComputedStyle(document.querySelector('.desktop')!).backgroundImage,
  }))
  await expect(wallpaper).toHaveValue('palette')
  const original=await appearance(),backgrounds=new Set<string>()
  for(const id of ['photo','poster','nocturne','ink','material','atmosphere','planes','topography','b-grid','b-monolith','b-horizon']){
    await wallpaper.selectOption(id)
    await expect(root).toHaveAttribute('data-wallpaper-choice',id)
    const current=await appearance()
    expect(current.primary).toBe(original.primary)
    expect(current.background).not.toBe(original.background)
    backgrounds.add(current.background)
    await expect(icon).toHaveAttribute('href',artwork!)
  }
  expect(backgrounds.size).toBe(11)
  const selected=await appearance()
  await palette.selectOption('iris')
  await material.uncheck()
  await expect(root).toHaveAttribute('data-palette','iris')
  await expect(root).toHaveAttribute('data-translucency','off')
  expect((await appearance()).background).toBe(selected.background)
  await page.reload()
  await expect(wallpaper).toHaveValue('b-horizon')
  await expect(palette).toHaveValue('iris')
  await expect(material).not.toBeChecked()
  expect((await appearance()).background).toBe(selected.background)
  await expect(icon).toHaveAttribute('href',artwork!)
  await wallpaper.selectOption('palette')
  const themeBackground=(await appearance()).background
  expect(themeBackground).not.toBe(selected.background)
  await palette.selectOption('ice')
  expect((await appearance()).background).toBe(original.background)
  expect(errors).toEqual([])
})

test('workspaces keep independent windows and model bodies through copy, switch and reload',async({page})=>{
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message))
  await page.goto('/');await page.locator('[data-app="blora.editor"]').click()
  await page.getByRole('textbox',{name:'文件正文编辑器'}).focus();await page.keyboard.insertText('原工作区草稿')
  const original=await page.locator('[data-view-tab]').getAttribute('data-view-tab')
  await page.getByRole('button',{name:'切换工作区'}).click();await page.getByRole('textbox',{name:'新工作区名称'}).fill('独立副本');await page.getByRole('button',{name:'复制当前现场'}).click()
  await expect(page.getByRole('dialog',{name:'工作区'})).toBeHidden()
  await page.getByRole('textbox',{name:'文件正文编辑器'}).focus();await pressEditorKey(page,'End');await page.keyboard.insertText('，副本新输入')
  await page.reload();await expect(page.locator('.monaco-editor .view-lines')).toContainText('副本新输入')
  await page.getByRole('button',{name:'切换工作区'}).click();await page.getByRole('dialog',{name:'工作区'}).getByRole('button',{name:'个人桌面',exact:true}).click()
  await expect(page.locator(`[data-view-tab="${original}"]`)).toHaveCount(1);await expect(page.locator('.monaco-editor .view-lines')).toContainText('原工作区草稿');await expect(page.locator('.monaco-editor .view-lines')).not.toContainText('副本新输入')
  await page.getByRole('button',{name:'关闭窗口',exact:true}).click();await page.getByRole('button',{name:'重新打开最近标签'}).click()
  await expect(page.locator(`[data-view-tab="${original}"]`)).toHaveCount(1);await expect(page.locator('.monaco-editor .view-lines')).toContainText('原工作区草稿');expect(errors).toEqual([])
})

test('all eight resize handles and snapped restore preserve geometry without remote operations',async({page})=>{
  await page.goto('/');await page.locator('[data-app="blora.instances"]').click()
  const win=page.locator('.app-window'),initial=await win.boundingBox()
  for(const direction of ['n','ne','e','se','s','sw','w','nw']){
    const handle=await win.locator(`[data-resize="${direction}"]`).boundingBox();const start={x:handle!.x+handle!.width/2,y:handle!.y+handle!.height/2}
    await page.mouse.move(start.x,start.y);await page.mouse.down();await page.mouse.move(start.x+(direction.includes('w')?-9:direction.includes('e')?9:0),start.y+(direction.includes('n')?-4:direction.includes('s')?4:0));await page.mouse.up()
  }
  expect((await win.boundingBox())!.width).toBeGreaterThan(initial!.width)
  const title=await win.locator('.window-titlebar').boundingBox()
  await page.mouse.move(title!.x+220,title!.y+19);await page.mouse.down();await page.mouse.move(5,200);await expect(page.locator('.snap-preview.left')).toBeVisible();await page.mouse.up()
  await expect(win).toHaveClass(/snapped/);await page.reload();await expect(page.locator('.app-window')).toHaveClass(/snapped/)
  await page.getByRole('button',{name:'最大化或还原窗口'}).click();await expect(page.locator('.app-window')).not.toHaveClass(/snapped/)
  await page.locator('.taskbar-app').click();await expect(page.locator('.app-window')).toBeHidden();await page.locator('.taskbar-app').click();await expect(page.locator('.app-window')).toBeVisible()
})

test('copying a browser tab creates an isolated branch and immediate typing keeps original unchanged',async({page,context})=>{
  await page.goto('/');await page.locator('[data-app="blora.editor"]').click();await page.getByRole('textbox',{name:'文件正文编辑器'}).focus();await page.keyboard.insertText('来源草稿')
  const storage=await page.evaluate(()=>Object.fromEntries(Object.entries(sessionStorage)))
  const duplicate=await context.newPage()
  await duplicate.route('**/api/v1/**',route=>route.fulfill({json:route.request().url().endsWith('/session')?{user:{userId:'browser-test',name:'测试用户',admin:true},csrfToken:'test-only'}:{items:[]}}))
  await duplicate.addInitScript(values=>{if(!sessionStorage.getItem('branch-seeded')){for(const [key,value] of Object.entries(values))sessionStorage.setItem(key,value);sessionStorage.setItem('branch-seeded','1')}},storage)
  await duplicate.goto('/');await expect(duplicate.locator('.monaco-editor .view-lines')).toContainText('来源草稿')
  expect(await duplicate.evaluate(()=>sessionStorage.getItem('blora:tab'))).not.toBe(await page.evaluate(()=>sessionStorage.getItem('blora:tab')))
  await duplicate.getByRole('textbox',{name:'文件正文编辑器'}).focus();await pressEditorKey(duplicate,'End');await duplicate.keyboard.insertText('分支输入');await duplicate.reload();await expect(duplicate.locator('.monaco-editor .view-lines')).toContainText('分支输入')
  await page.reload();await expect(page.locator('.monaco-editor .view-lines')).not.toContainText('分支输入');await duplicate.close()
})

test('native Chromium IME composition survives immediate reload',async({page,context,browserName})=>{
  test.skip(browserName!=='chromium','Native composition injection requires CDP; Firefox/WebKit native IME remains unverified.')
  await page.goto('/');await page.locator('[data-app="blora.editor"]').click();await page.getByRole('textbox',{name:'文件正文编辑器'}).focus()
  const input=await context.newCDPSession(page)
  await input.send('Input.imeSetComposition',{text:'中文组合',selectionStart:4,selectionEnd:4})
  await input.send('Input.insertText',{text:'中文组合'})
  await page.reload();await expect(page.locator('.monaco-editor .view-lines')).toContainText('中文组合')
})

test('committed Unicode, simultaneous multi-cursor edits and find state survive immediate reload',async({page})=>{
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message))
  await page.goto('/');await page.locator('[data-app="blora.editor"]').click();await page.getByRole('textbox',{name:'文件正文编辑器'}).focus()
  await page.keyboard.insertText('中文组合')
  await page.keyboard.insertText('\nmatch\nmatch')
  await page.reload();await expect(page.locator('.monaco-editor .view-lines')).toContainText('中文组合')
  await page.getByRole('button',{name:'查找',exact:true}).click();await page.getByRole('textbox',{name:'查找内容',exact:true}).fill('match');await page.getByRole('textbox',{name:'替换内容',exact:true}).fill('替换草稿')
  await expect(page.getByRole('textbox',{name:'查找内容',exact:true})).toHaveValue('match');await expect(page.getByRole('textbox',{name:'替换内容',exact:true})).toHaveValue('替换草稿')
  await page.getByRole('button',{name:'选择全部匹配',exact:true}).click();await page.keyboard.insertText('双光标')
  // Native EditContext can emit one semantic edit per character for a multi-cursor
  // insertion. Compare the actual available undo history before and after reload.
  const lines=page.locator('.monaco-editor .view-lines')
  await expect(lines).toContainText('双光标');const beforeUndo=await lines.innerText()
  await page.getByRole('textbox',{name:'文件正文编辑器'}).focus();await pressEditorKey(page,'z')
  // Monaco paints asynchronously in WebKit. Reading innerText immediately
  // after the key can capture the pre-undo frame as the expected undo result.
  await expect(lines).not.toHaveText(beforeUndo,{useInnerText:true});const priorUndo=await lines.innerText()
  await pressEditorKey(page,'y');await expect(lines).toHaveText(beforeUndo,{useInnerText:true})
  await page.reload();await expect(page.locator('.monaco-editor .view-lines')).toContainText('中文组合');await expect(page.locator('.monaco-editor .view-lines')).toContainText('双光标')
  await expect(page.getByRole('textbox',{name:'查找内容',exact:true})).toHaveValue('match');await expect(page.getByRole('textbox',{name:'替换内容',exact:true})).toHaveValue('替换草稿')
  await page.getByRole('textbox',{name:'文件正文编辑器'}).focus();await pressEditorKey(page,'z');await expect(page.locator('.monaco-editor .view-lines')).toHaveText(priorUndo,{useInnerText:true})
  await pressEditorKey(page,'y');await expect(page.locator('.monaco-editor .view-lines')).toContainText('双光标');expect(errors).toEqual([])
})
