import {test,expect} from '@playwright/test'
import {selectStyledOption} from '../helpers/styled-select'
test('per-view filters and fixed batch requests recover partial acceptance without replay',async({page})=>{
  let requests:{path:string;key:string}[]=[],renamed=false,revoked=false
  const first={instanceId:'batch-one',nodeId:'batch-node-one',nodeName:'节点甲',name:'实例甲',state:'STOPPED',group:'games',tags:['中文'],config:{},revision:1},second={...first,instanceId:'batch-two',nodeId:'batch-node-two',nodeName:'节点乙',name:'实例乙',group:'tools',tags:['运维']}
  const task={taskId:'batch-task',action:'start',state:'WAITING_NODE',phase:'waiting',resource:{kind:'instance',id:first.instanceId}}
  await page.route('**/api/v1/**',route=>{
    const path=new URL(route.request().url()).pathname;let json:unknown={items:[]}
    if(path.endsWith('/session'))json={user:{userId:'batch-user',name:'批量测试',admin:false},csrfToken:'test-only'}
    else if(path.endsWith('/instances'))json={items:[...revoked?[]:[{...first,name:renamed?'实例甲改名':first.name}],second]}
    else if(path.endsWith('/actions')){requests.push({path,key:route.request().headers()['idempotency-key']!});if(path.includes(second.instanceId))return route.fulfill({status:403,json:{error:{code:'FORBIDDEN',message:'第二实例未获启动权限'}}});json={task:{...task,requestId:requests[0]!.key}}}
    else if(path.endsWith('/tasks'))json={items:requests.length?[{...task,requestId:requests[0]!.key}]:[]}
    return route.fulfill({json})
  })
  await page.goto('/');await page.locator('[data-app="blora.instances"]').click();const nodeFilter=page.getByRole('combobox',{name:'节点筛选'});await nodeFilter.click();await expect(page.getByRole('option')).toHaveCount(3);await page.keyboard.press('Escape');await selectStyledOption(page,page.getByRole('combobox',{name:'实例分组筛选'}),'games');await selectStyledOption(page,page.getByRole('combobox',{name:'实例标签筛选'}),'中文');await page.reload();await expect(page.locator('.instance-card')).toHaveCount(1);await page.getByRole('button',{name:'卡片',exact:true}).click();await expect(page.locator('.instance-grid.cards')).toBeVisible();await page.reload();await expect(page.getByRole('button',{name:'卡片',exact:true})).toHaveAttribute('aria-pressed','true');await page.getByRole('button',{name:'列表',exact:true}).click();await page.getByRole('button',{name:'选择当前筛选全部',exact:true}).click();await selectStyledOption(page,page.getByRole('combobox',{name:'实例分组筛选'}),'');await selectStyledOption(page,page.getByRole('combobox',{name:'实例标签筛选'}),'');await page.getByRole('checkbox',{name:'选择实例 实例乙',exact:true}).check();await page.getByRole('button',{name:'批量启动',exact:true}).click();await page.reload();expect(requests).toEqual([]);await expect(page.getByRole('dialog')).toContainText(first.nodeId);await expect(page.getByRole('dialog')).toContainText(second.nodeId);await page.getByRole('button',{name:'确认提交未接受项',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('WAITING_NODE');await expect(page.getByRole('dialog')).toContainText('第二实例未获启动权限');await page.reload();expect(requests).toHaveLength(2);await page.getByRole('button',{name:'确认提交未接受项',exact:true}).click();await expect.poll(()=>requests.length).toBe(3);expect(requests[2]).toEqual(requests[1]);expect(requests.filter(request=>request.path.includes(first.instanceId))).toHaveLength(1)
  await page.getByRole('button',{name:'关闭批量确认',exact:true}).click();await page.getByRole('button',{name:'实例甲',exact:true}).click();await page.getByRole('button',{name:'＋ 添加到桌面',exact:true}).click();await page.locator('.app-window.focused').getByRole('button',{name:'关闭窗口',exact:true}).click();const shortcut=page.locator('[data-shortcut]');await expect(shortcut).toContainText('STOPPED');renamed=true;await expect(shortcut).toContainText('实例甲改名',{timeout:10000});revoked=true;await expect(shortcut).toContainText('不可访问',{timeout:10000});await shortcut.click();await expect(page.locator('.app-window.focused')).toContainText('无法读取此实例');expect(requests).toHaveLength(3)
})
