import {test,expect} from '@playwright/test'
test('versioned instance settings and template creation retain exact requests through lost receipts',async({page})=>{
  const patches:{key:string;body:Record<string,unknown>}[]=[],creates:{key:string;body:Record<string,unknown>}[]=[],actions:string[]=[],errors:string[]=[]
  const node={nodeId:'config-node',name:'配置节点',state:'ONLINE',platform:'linux',capabilities:{container:'available'},revision:1}
  let instance={instanceId:'config-instance',nodeId:node.nodeId,name:'配置实例',group:'',tags:[],state:'STOPPED',configRevision:4,revision:8,config:{mode:'native',command:['/bin/sh','-c','printf hello'],directory:'.',stopSeconds:30,killSeconds:10,stopInput:'',escalate:true,autostart:false}}
  let created:typeof instance|undefined
  page.on('pageerror',error=>errors.push(error.message))
  await page.route('**/api/v1/**',route=>{
    const path=new URL(route.request().url()).pathname,method=route.request().method();let json:unknown={items:[]}
    if(path.endsWith('/session'))json={user:{userId:'configuration-user',name:'配置管理员',admin:true},csrfToken:'test-only'}
    else if(path.endsWith('/nodes')||path.endsWith('/nodes/creatable'))json={items:[node]}
    else if(path.endsWith('/instance-templates'))json={items:[{templateId:'java-game',name:'Java 游戏服务',platform:'any',description:'配置测试模板',config:{mode:'native',command:['java','-jar','server.jar'],directory:'.',stopSeconds:120,killSeconds:10,stopInput:'stop\n',escalate:true,autostart:false}}]}
    else if(path.endsWith('/instances')&&method==='POST'){creates.push({key:route.request().headers()['idempotency-key']!,body:route.request().postDataJSON()});created={...instance,...creates[0]!.body,instanceId:'new-config-instance',configRevision:1} as typeof instance;if(creates.length===1)return route.abort('connectionreset');json={instance:created}}
    else if(path.endsWith('/instances'))json={items:[instance,...created?[created]:[]]}
    else if(path.endsWith('/instances/config-instance')){if(method==='PATCH'){patches.push({key:route.request().headers()['idempotency-key']!,body:route.request().postDataJSON()});if(patches.length===1){instance={...instance,...patches[0]!.body,configRevision:5} as typeof instance;return route.abort('connectionreset')}}json={instance}}
    else if(path.endsWith('/actions'))actions.push(path)
    return route.fulfill({json})
  })
  await page.goto('/');await page.locator('[data-app="blora.instances"]').click();await page.getByRole('button',{name:'配置实例',exact:true}).click();await page.locator('.resource-nav').getByRole('button',{name:'设置',exact:true}).click();await page.getByRole('textbox',{name:'实例名称',exact:true}).fill('重命名草稿');await page.getByRole('checkbox',{name:'同时修改运行配置',exact:true}).check();await page.getByRole('textbox',{name:'启动参数 2',exact:true}).fill('printf "参数含空格"\nread answer');await page.getByRole('textbox',{name:'正常停止输入',exact:true}).fill('quit\n');await page.getByRole('spinbutton',{name:'正常停止期限（秒）',exact:true}).fill('22');await page.getByRole('button',{name:'添加环境变量',exact:true}).click();await page.getByRole('textbox',{name:'环境变量名称 1',exact:true}).fill('LANG');await page.getByRole('textbox',{name:'环境变量值 1',exact:true}).fill('zh_CN.UTF-8');await page.reload();await expect(page.getByRole('textbox',{name:'启动参数 2',exact:true})).toHaveValue('printf "参数含空格"\nread answer');await expect(page.getByRole('textbox',{name:'环境变量值 1',exact:true})).toHaveValue('zh_CN.UTF-8');expect(patches).toEqual([])
  await page.getByRole('button',{name:'核对配置变更',exact:true}).click();await page.reload();await expect(page.getByRole('dialog',{name:'确认实例配置'})).toContainText('config-instance');await page.getByRole('button',{name:'确认保存配置',exact:true}).click();await expect(page.getByRole('dialog').locator('.error')).toBeVisible();await page.reload();expect(patches).toHaveLength(1);await page.getByRole('button',{name:'确认保存配置',exact:true}).click();await expect(page.getByRole('status')).toContainText('配置已保存');expect(patches[1]).toEqual(patches[0]);expect(patches[0]!.body.revision).toBe(4)
  await page.locator('.app-window.focused').getByRole('button',{name:'关闭窗口',exact:true}).click();await page.locator('[data-app="blora.instances"]').click();await page.getByRole('button',{name:'创建实例',exact:true}).click();await page.getByRole('textbox',{name:'名称',exact:true}).fill('模板创建草稿');await page.getByRole('combobox',{name:'目标节点',exact:true}).selectOption(node.nodeId);await page.getByRole('combobox',{name:'配置模板',exact:true}).selectOption('java-game');await page.reload();await expect(page.getByRole('textbox',{name:'正常停止输入',exact:true})).toHaveValue('stop\n');await page.getByRole('button',{name:'核对创建实例',exact:true}).click();await page.reload();expect(creates).toEqual([])
  await page.getByRole('button',{name:'确认创建实例',exact:true}).click();await expect(page.getByRole('dialog').locator('.error')).toBeVisible();await page.reload();expect(creates).toHaveLength(1);await page.getByRole('button',{name:'确认创建实例',exact:true}).click();await expect(page.getByRole('dialog',{name:'创建实例'})).toHaveCount(0);await expect(page.locator('.resource-heading')).toContainText('模板创建草稿');expect(creates[1]).toEqual(creates[0]);expect((creates[0]!.body.config as {command:string[]}).command).toEqual(['java','-jar','server.jar']);expect(actions).toEqual([]);expect(errors).toEqual([])
})
