import { createApp } from 'vue'
import { createPinia } from 'pinia'
import { VueQueryPlugin, QueryClient } from '@tanstack/vue-query'
import App from './App.vue'
import './apps/register'
import './style.css'
import './applications.css'
import './appearance/preview'
import './appearance/ice.css'
import './appearance/color-palettes.css'
import './appearance/palette-wallpapers.css'
import './appearance/wallpaper-styles.css'
import './appearance/dark-surfaces.css'
import './appearance/dark-apps.css'
createApp(App).use(createPinia()).use(VueQueryPlugin, { queryClient: new QueryClient({ defaultOptions: { queries: { retry: 1, staleTime: 1500 } } }) }).mount('#app')
