import {realLogin} from './login'
import {readFileSync} from 'node:fs'
import {randomUUID} from 'node:crypto'
import {test,expect,type Page} from '@playwright/test'
import {decodeEnvelope,decodeJSON,MessageType} from '../../src/services/protocol'
const fixture=JSON.parse(readFileSync(process.env.BLORA_E2E_CREDENTIALS!,'utf8')) as {admin:{name:string;password:string};member:{name:string;password:string};instanceIds:string[]}
async function login(page:Page,role:'admin'|'member'='admin'){await realLogin(page,fixture[role])}
async function headers(page:Page){return{'X-CSRF-Token':(await(await page.request.get('/api/v1/session')).json()).csrfToken,'Idempotency-Key':randomUUID()}}
async function task(page:Page,id:string){await expect.poll(async()=>(await(await page.request.get(`/api/v1/tasks/${id}`)).json()).task.state,{timeout:30000}).toBe('SUCCEEDED')}
async function open(page:Page,id:string,section:'文件'|'控制台'){const instance=(await(await page.request.get('/api/v1/instances')).json()).items.find((item:{instanceId:string})=>item.instanceId===id);await page.locator('[data-app="blora.instances"]').click();await page.locator('.app-window.focused').getByRole('button',{name:instance.name,exact:true}).click();await page.locator('.app-window.focused').getByRole('button',{name:section,exact:true}).click();if(section==='文件')await page.locator('.app-window.focused').getByRole('button',{name:'在文件管理器打开',exact:true}).click()}
const files=(id:string)=>`/api/v1/instances/${id}/files`
async function write(page:Page,id:string,path:string,text:string){const response=await page.request.put(`${files(id)}/content`,{headers:await headers(page),data:{path,text,version:'missing'}});expect(response.status()).toBe(202);await task(page,(await response.json()).task.taskId)}
async function textAt(page:Page,id:string,path:string){const response=await page.request.get(`${files(id)}/content?path=${encodeURIComponent(path)}`);expect(response.ok()).toBeTruthy();return(await response.json()).text}

test('actual cross-node directory copy and move verify destination before removing source',async({page})=>{
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));await login(page)
  const [sourceId,targetId]=fixture.instanceIds as [string,string],directory=`browser-transfer-${randomUUID()}`,moved=directory+'-moved'
  const created=await page.request.post(`${files(sourceId)}/actions`,{headers:await headers(page),data:{action:'mkdir',path:directory,target:directory,targetVersion:'missing'}});expect(created.status()).toBe(202);await task(page,(await created.json()).task.taskId)
  await write(page,sourceId,`${directory}/first.txt`,'跨节点正文中文');await write(page,sourceId,`${directory}/second.txt`,'第二份内容\n'.repeat(16000))
  await open(page,sourceId,'文件');await page.locator('.file-row').filter({hasText:directory}).click();await page.getByRole('button',{name:'复制',exact:true}).click();await expect(page.locator('.file-clipboard')).toContainText('复制 1 项')
  await page.locator('.app-window.focused').getByRole('button',{name:'关闭窗口',exact:true}).click();await page.locator('.app-window.focused').getByRole('button',{name:'关闭窗口',exact:true}).click();await open(page,targetId,'文件');await page.getByRole('button',{name:'粘贴',exact:true}).click();await page.reload();await expect(page.getByRole('dialog')).toContainText(sourceId);await expect(page.getByRole('dialog')).toContainText(targetId)
  const accepted=page.waitForResponse(response=>response.url().endsWith('/api/v1/transfers')&&response.request().method()==='POST');await page.getByRole('button',{name:'确认文件操作',exact:true}).click();const copyReply=await accepted;expect(copyReply.status()).toBe(202);const copyId=(await copyReply.json()).task.taskId;await task(page,copyId)
  expect(await textAt(page,targetId,`${directory}/first.txt`)).toBe('跨节点正文中文');expect(await textAt(page,targetId,`${directory}/second.txt`)).toBe('第二份内容\n'.repeat(16000));expect(await textAt(page,sourceId,`${directory}/first.txt`)).toBe('跨节点正文中文')
  await page.getByRole('button',{name:'刷新',exact:true}).click();await page.locator('.file-row').filter({hasText:directory}).click();await page.getByRole('button',{name:'剪切',exact:true}).click();await expect(page.locator('.file-clipboard')).toContainText('剪切 1 项');await page.locator('.app-window.focused').getByRole('button',{name:'关闭窗口',exact:true}).click();await page.locator('.app-window.focused').getByRole('button',{name:'关闭窗口',exact:true}).click()
  await open(page,sourceId,'文件');await page.getByRole('button',{name:'粘贴',exact:true}).click();await page.getByRole('textbox',{name:'文件操作目标'}).fill(moved);await expect(page.getByRole('dialog')).toContainText('先复制、验证目标');const moving=page.waitForResponse(response=>response.url().endsWith('/api/v1/transfers')&&response.request().method()==='POST');await page.getByRole('button',{name:'确认文件操作',exact:true}).click();const moveId=(await(await moving).json()).task.taskId;await task(page,moveId)
  expect(await textAt(page,sourceId,`${moved}/second.txt`)).toBe('第二份内容\n'.repeat(16000));expect((await page.request.get(`${files(targetId)}/stat?path=${directory}`)).status()).toBe(404)
  await page.getByRole('button',{name:'详情',exact:true}).click();await expect(page.getByRole('region',{name:'文件传输阶段'})).toContainText('目标内容已验证');await expect(page.getByRole('region',{name:'文件传输阶段'})).toContainText('源已删除');const result=(await(await page.request.get(`/api/v1/transfers/${moveId}`)).json()).transfer;expect(result.destinationVerified).toBe(true);expect(result.sourceDeleted).toBe(true);expect(result.sourceOutcomeUnknown).toBeFalsy();expect(errors).toEqual([])
})

test('actual instance logs restore cursors and authorized stdin delivery does not replay',async({page,browser})=>{
  await login(page);const id=fixture.instanceIds[0]!,instance=(await(await page.request.get('/api/v1/instances')).json()).items.find((item:{instanceId:string})=>item.instanceId===id)
  const start=await page.request.post(`/api/v1/instances/${id}/actions`,{headers:await headers(page),data:{action:'start'}});expect(start.status()).toBe(202);await task(page,(await start.json()).task.taskId)
  const observerContext=await browser.newContext({ignoreHTTPSErrors:true}),observer=await observerContext.newPage(),posts:string[]=[],cursors:number[]=[];let latest=0;const member=(await(await page.request.get('/api/v1/users')).json()).items.find((user:{name:string})=>user.name===fixture.member.name),inputGrant={userId:member.userId,resource:{kind:'instance',id,nodeId:instance.nodeId},action:'terminal.input'};await page.request.delete('/api/v1/grants',{headers:await headers(page),data:inputGrant})
  observer.on('request',request=>{if(request.method()==='POST'&&request.url().includes('/logs/'))posts.push(request.postData()!)});observer.on('websocket',socket=>{if(!socket.url().includes('/logs/'))return;cursors.push(Number(new URL(socket.url()).searchParams.get('sequence')));socket.on('framereceived',event=>{if(typeof event.payload==='string')return;const frame=decodeEnvelope(new Uint8Array(event.payload));if(frame.type===MessageType.Data)latest=decodeJSON<{sequence:number}>(frame.payload).sequence})})
  try{
    await login(observer,'member');await open(observer,id,'控制台');await expect(observer.getByRole('log',{name:'实例运行日志'})).toContainText('中文-BLORA-INSTANCE-LOG',{timeout:30000});await expect(observer.getByRole('button',{name:'发送命令',exact:true})).toBeDisabled()
    const runId=(await(await page.request.get('/api/v1/instances')).json()).items.find((item:{instanceId:string})=>item.instanceId===id).runId
    const denied=await observer.request.post(`/api/v1/instances/${id}/logs/${runId}/input`,{headers:await headers(observer),data:{data:'denied\n'}});expect(denied.status()).toBe(403)
    const grant=await page.request.post('/api/v1/grants',{headers:await headers(page),data:inputGrant});expect(grant.status()).toBe(200)
    await observer.reload();const command='browser-input-'+randomUUID();await observer.getByRole('textbox',{name:'尚未发送的实例命令'}).fill(command);await observer.getByRole('button',{name:'发送命令',exact:true}).click();await expect(observer.getByRole('log',{name:'实例运行日志'})).toContainText('CONSOLE:'+command,{timeout:30000});await expect(observer.locator('.console-input-result')).toContainText('不代表程序处理成功',{timeout:30000})
    await observer.getByRole('textbox',{name:'尚未发送的实例命令'}).fill('下一条未发命令');await observer.getByRole('textbox',{name:'搜索保留日志'}).fill(command);await observer.getByRole('button',{name:'暂停跟随输出',exact:true}).click();const before=latest,priorConnections=cursors.length;await observer.reload();await expect(observer.getByRole('log',{name:'实例运行日志'})).toContainText('CONSOLE:'+command);await expect(observer.getByRole('textbox',{name:'尚未发送的实例命令'})).toHaveValue('下一条未发命令');await expect.poll(()=>cursors.length).toBe(priorConnections+1);expect(cursors.at(-1)).toBe(before);expect(posts).toHaveLength(1)
    await observer.getByRole('textbox',{name:'搜索保留日志'}).fill('');const stop=await page.request.post(`/api/v1/instances/${id}/actions`,{headers:await headers(page),data:{action:'stop'}});expect(stop.status()).toBe(202);await task(page,(await stop.json()).task.taskId);await expect(observer.locator('.instance-console')).toContainText('日志归档已完成',{timeout:30000});await expect(observer.getByRole('button',{name:'发送命令',exact:true})).toBeDisabled();expect(posts).toHaveLength(1)
  }finally{if(inputGrant)await page.request.delete('/api/v1/grants',{headers:await headers(page),data:inputGrant});await observerContext.close();const stop=await page.request.post(`/api/v1/instances/${id}/actions`,{headers:await headers(page),data:{action:'stop'}});if(stop.status()===202)await task(page,(await stop.json()).task.taskId)}
})
