import {readFileSync} from 'node:fs'
import {randomUUID} from 'node:crypto'
import {test,expect} from '@playwright/test'
import {selectStyledOption} from '../helpers/styled-select'
import {realLogin} from './login'
const fixture=JSON.parse(readFileSync(process.env.BLORA_E2E_CREDENTIALS!,'utf8')) as {admin:{name:string;password:string};instanceIds:string[]}
// Runs after tests which assert the two seed instances. The parent retires this
// disposable fixture afterwards; it never starts this additional test instance.
test('actual template creation is idempotent and never implicitly starts its process',async({page})=>{
  await realLogin(page,fixture.admin);const session=(await(await page.request.get('/api/v1/session')).json()),initial=(await(await page.request.get('/api/v1/instances')).json()).items,source=initial.find((instance:{instanceId:string})=>instance.instanceId===fixture.instanceIds[0]),suffix=randomUUID(),name='浏览器模板创建-'+suffix,path='created-instance-'+suffix
  const mkdir=await page.request.post(`/api/v1/instances/${source.instanceId}/files/actions`,{headers:{'X-CSRF-Token':session.csrfToken,'Idempotency-Key':randomUUID()},data:{action:'mkdir',path,target:path,targetVersion:'missing'}});expect(mkdir.status()).toBe(202);const mkdirTask=(await mkdir.json()).task.taskId;await expect.poll(async()=>(await(await page.request.get(`/api/v1/tasks/${mkdirTask}`)).json()).task.state,{timeout:30000}).toBe('SUCCEEDED')
  const actions:string[]=[],posts:string[]=[];page.on('request',request=>{if(request.method()==='POST'&&/\/instances\/[^/]+\/actions$/.test(request.url()))actions.push(request.url());if(request.method()==='POST'&&request.url().endsWith('/api/v1/instances'))posts.push(request.postData()!)})
  await page.locator('[data-app="blora.instances"]').click();await page.getByRole('button',{name:'创建实例',exact:true}).click();await page.getByRole('textbox',{name:'名称',exact:true}).fill(name);await selectStyledOption(page,page.getByRole('combobox',{name:'目标节点',exact:true}),source.nodeId);await selectStyledOption(page,page.getByRole('combobox',{name:'配置模板',exact:true}),'native-linux');await page.getByRole('textbox',{name:'可执行程序',exact:true}).fill('/bin/sh');await page.getByRole('textbox',{name:'工作目录',exact:true}).fill(source.config.directory.replace(/\/$/,'')+'/'+path);await page.getByRole('button',{name:'添加启动参数',exact:true}).click();await page.getByRole('textbox',{name:'启动参数 1',exact:true}).fill('-c');await page.getByRole('button',{name:'添加启动参数',exact:true}).click();await page.getByRole('textbox',{name:'启动参数 2',exact:true}).fill('printf "created-but-not-started\\n"');await page.getByRole('button',{name:'核对创建实例',exact:true}).click();await page.reload();expect(posts).toEqual([])
  const response=page.waitForResponse(response=>response.url().endsWith('/api/v1/instances')&&response.request().method()==='POST');await page.getByRole('button',{name:'确认创建实例',exact:true}).click();const accepted=await response;expect(accepted.status()).toBe(201);const created=(await accepted.json()).instance;await expect(page.locator('.resource-heading')).toContainText(name);expect(created.state).toBe('STOPPED');expect(created.config.autostart).toBe(false);expect(created.config.command).toEqual(['/bin/sh','-c','printf "created-but-not-started\\n"'])
  const replay=await page.request.post('/api/v1/instances',{headers:{'X-CSRF-Token':session.csrfToken,'Idempotency-Key':accepted.request().headers()['idempotency-key']!},data:accepted.request().postDataJSON()});expect(replay.status()).toBe(201);expect((await replay.json()).instance.instanceId).toBe(created.instanceId);const final=(await(await page.request.get('/api/v1/instances')).json()).items;expect(final).toHaveLength(initial.length+1);expect(final.find((instance:{instanceId:string})=>instance.instanceId===created.instanceId).state).toBe('STOPPED');expect(actions).toEqual([]);expect(posts).toHaveLength(1)
})
